import type { ConversationItem, ThreadSummary } from "../../../types";
import { previewThreadName } from "../../../utils/threadItems";

function formatThreadName(text: string) {
  const trimmed = text.trim();
  if (!trimmed) {
    return null;
  }
  return trimmed;
}

export function looksAutoGeneratedThreadName(name: string) {
  return name.startsWith("Agent ") || /^[a-f0-9]{4,8}$/i.test(name);
}

function looksGenericSessionFallbackName(name: string) {
  const normalized = name.trim().toLowerCase();
  return (
    normalized === "codex session"
    || normalized === "claude session"
    || normalized === "gemini session"
    || normalized === "opencode session"
  );
}

export function shouldPreferExistingThreadName(
  existingName: string,
  incomingName: string,
) {
  const existingAutoGenerated = looksAutoGeneratedThreadName(existingName);
  const incomingAutoGenerated = looksAutoGeneratedThreadName(incomingName);
  if (incomingAutoGenerated && !existingAutoGenerated) {
    return true;
  }
  const existingGenericFallback = looksGenericSessionFallbackName(existingName);
  const incomingGenericFallback = looksGenericSessionFallbackName(incomingName);
  if (incomingGenericFallback && !existingAutoGenerated && !existingGenericFallback) {
    return true;
  }
  return false;
}

export function extractRenameText(text: string) {
  if (!text) {
    return "";
  }
  const withoutImages = text.replace(/\[image(?: x\d+)?\]/gi, " ");
  const withoutSkills = withoutImages.replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ");
  return previewThreadName(withoutSkills, "");
}

export function isRetainableFinalizedCodexThread(thread: ThreadSummary) {
  if (thread.threadKind === "shared") {
    return false;
  }
  const engineSource = thread.engineSource ?? "codex";
  if (engineSource !== "codex") {
    return false;
  }
  return !thread.id.trim().toLowerCase().startsWith("codex-pending-");
}

function isAssistantMessageItem(
  item: ConversationItem | undefined,
): item is Extract<ConversationItem, { kind: "message" }> & { role: "assistant" } {
  return item?.kind === "message" && item.role === "assistant";
}

function getAssistantTextForRename(
  items: ConversationItem[],
  itemId?: string,
): string {
  if (itemId) {
    const match = items.find(
      (item) =>
        item.kind === "message" &&
        item.role === "assistant" &&
        item.id === itemId,
    );
    if (isAssistantMessageItem(match)) {
      return match.text;
    }
  }
  for (let index = items.length - 1; index >= 0; index -= 1) {
    const item = items[index];
    if (!item) {
      continue;
    }
    if (isAssistantMessageItem(item)) {
      return item.text;
    }
  }
  return "";
}

export function maybeRenameThreadFromAgent({
  workspaceId,
  threadId,
  items,
  itemId,
  hasCustomName,
  threadsByWorkspace,
}: {
  workspaceId: string;
  threadId: string;
  items: ConversationItem[];
  itemId?: string;
  hasCustomName: boolean;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
}) {
  const threads = threadsByWorkspace[workspaceId] ?? [];
  if (!threads.length) {
    return threadsByWorkspace;
  }
  const hasUserMessage = items.some(
    (item) => item.kind === "message" && item.role === "user",
  );
  if (hasUserMessage) {
    return threadsByWorkspace;
  }
  if (hasCustomName) {
    return threadsByWorkspace;
  }
  const nextName = formatThreadName(getAssistantTextForRename(items, itemId));
  if (!nextName) {
    return threadsByWorkspace;
  }
  let didChange = false;
  const nextThreads = threads.map((thread) => {
    if (
      thread.id !== threadId ||
      thread.name === nextName ||
      !looksAutoGeneratedThreadName(thread.name)
    ) {
      return thread;
    }
    didChange = true;
    return { ...thread, name: nextName };
  });
  return didChange
    ? { ...threadsByWorkspace, [workspaceId]: nextThreads }
    : threadsByWorkspace;
}
