import type { ConversationItem, ThreadSummary } from "../../../types";
import type { SidebarSnapshot } from "../utils/sidebarSnapshot";
import {
  normalizeItem,
  prepareThreadItems,
  upsertItem,
} from "../../../utils/threadItems";
import { settlePlanInProgressSteps } from "../utils/threadNormalize";
import {
  isIncrementalDerivationEnabled,
  isReducerNoopGuardEnabled,
} from "../utils/realtimePerfFlags";
import {
  buildLegacyTextDeltaItemId,
  findAssistantMessageIndexByLegacyTextDelta,
  findReasoningIndexById,
  insertLiveReasoningItem,
  isLegacyTextDeltaItemId,
} from "./threadReducerItemLookup";
import {
  isGeminiReasoningThread,
  shouldAcceptReasoningDelta,
} from "./threadReducerReasoningGuards";
import {
  addSummaryBoundary,
  findDuplicateReasoningSnapshotIndex,
  mergeAgentMessageText,
  mergeCompletedAgentText,
  mergeReasoningSnapshotTextForThread,
  mergeReasoningTextForThread,
  mergeStreamingText,
  normalizeReasoningReadableText,
} from "./threadReducerTextMerge";
import {
  findEquivalentCodexAssistantMessageIndex,
  shouldDeduplicateCodexAssistantMessages,
} from "./useThreadsReducerAssistantDedup";
import { isOptimisticUserMessageId } from "../utils/queuedHandoffBubble";
import {
  isProcessingGeneratedImageItem,
} from "../utils/generatedImagePlaceholder";
import {
  replaceMatchingProcessingGeneratedImage,
} from "../utils/generatedImagePlaceholderMatching";
import { reduceNormalizedRealtimeEvent } from "./threadReducerNormalizedRealtime";
import {
  insertGeneratedImagesAfterAnchors,
  replaceOptimisticUserAndExtractAnchoredGeneratedImages,
} from "./threadReducerOptimisticUserReconciliation";
import { isSameApprovalRequest } from "./threadReducerApprovalRequests";
import {
  clearAssistantFinalMetadata,
  shouldPreserveAssistantFinalMetadata,
} from "./threadReducerAssistantFinalMetadata";
import { mergeThreadItemsPreservingOptimisticUsers } from "./threadReducerOptimisticItemMerge";
import {
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  findMatchingReview,
  isDuplicateReviewById,
} from "./threadReducerReviewItems";
import { shouldFinalizeToolStatus } from "./threadReducerToolStatus";
import {
  extractRenameText,
  isRetainableFinalizedCodexThread,
  looksAutoGeneratedThreadName,
  maybeRenameThreadFromAgent,
  shouldPreferExistingThreadName,
} from "./threadReducerThreadNaming";
import {
  buildCodexCompactionMessage,
  canUseLiveAssistantDeltaFastPath,
  collectThreadScopedCodexCompactionMessages,
  filterThreadScopedCodexCompactionMessages,
  findAssistantMessageIndexById,
  findAssistantMessageIndexByPrefix,
  isAssistantMessageItem,
  isThreadScopedCodexCompactionMessage,
  isThreadTokenUsageEqual,
  isToolConversationItem,
  isUserMessageItem,
  resolveLiveAssistantMessageId,
  resolveLiveReasoningItemId,
  withThreadStatusDefaults,
} from "./threadReducerCoreHelpers";
import type {
  CodexCompactionLifecycleState,
  ThreadAction,
  ThreadState,
} from "./threadReducerTypes";
export type { ThreadAction, ThreadState } from "./threadReducerTypes";

const REDUCER_NOOP_GUARD_ENABLED = isReducerNoopGuardEnabled();
const INCREMENTAL_DERIVATION_ENABLED = isIncrementalDerivationEnabled();
const PENDING_THREAD_LAST_AGENT_ANCHOR_TTL_MS = 5 * 60 * 1000;
type GeneratedImageItem = Extract<ConversationItem, { kind: "generatedImage" }>;
const emptyItems: Record<string, ConversationItem[]> = {};

export const initialState: ThreadState = {
  activeThreadIdByWorkspace: {},
  itemsByThread: emptyItems,
  historyRestoredAtMsByThread: {},
  threadsByWorkspace: {},
  hiddenThreadIdsByWorkspace: {},
  threadParentById: {},
  threadStatusById: {},
  threadListLoadingByWorkspace: {},
  threadListPagingByWorkspace: {},
  threadListCursorByWorkspace: {},
  activeTurnIdByThread: {},
  codexAcceptedTurnByThread: {},
  approvals: [],
  userInputRequests: [],
  tokenUsageByThread: {},
  rateLimitsByWorkspace: {},
  accountByWorkspace: {},
  planByThread: {},
  lastAgentMessageByThread: {},
  agentSegmentByThread: {},
};

export function createInitialThreadState(snapshot?: SidebarSnapshot | null): ThreadState {
  if (!snapshot) {
    return initialState;
  }
  return {
    ...initialState,
    threadsByWorkspace: snapshot.threadsByWorkspace,
  };
}

export function threadReducer(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "setActiveThreadId":
      return {
        ...state,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: action.threadId,
        },
        threadStatusById: action.threadId
          ? {
              ...state.threadStatusById,
              [action.threadId]: {
                ...withThreadStatusDefaults(
                  state.threadStatusById[action.threadId],
                ),
                hasUnread: false,
              },
            }
          : state.threadStatusById,
      };
    case "ensureThread": {
      const hidden =
        state.hiddenThreadIdsByWorkspace[action.workspaceId]?.[action.threadId] ??
        false;
      if (hidden) {
        return state;
      }
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      let existingIndex = list.findIndex((thread) => thread.id === action.threadId);
      if (existingIndex < 0 && !action.threadId.includes(":")) {
        const aliasIndexes = list
          .map((thread, index) => ({ thread, index }))
          .filter(({ thread }) => thread.id.endsWith(`:${action.threadId}`))
          .map(({ index }) => index);
        if (aliasIndexes.length === 1) {
          existingIndex = aliasIndexes[0] ?? -1;
        }
      }
      if (existingIndex >= 0) {
        const existing = list[existingIndex];
        if (!existing) {
          return state;
        }
        // BUG FIX: Only update engineSource if action.engine is explicitly provided
        // AND the existing engineSource is not already set.
        // This prevents inferred engines (from inferEngineFromThreadId) from
        // overwriting explicitly set engines.
        if (!action.engine || existing.engineSource) {
          return state;
        }
        const updated = {
          ...existing,
          engineSource: action.engine,
          folderId: action.folderId ?? existing.folderId,
        };
        const nextList = [...list];
        nextList[existingIndex] = updated;
        return {
          ...state,
          threadsByWorkspace: {
            ...state.threadsByWorkspace,
            [action.workspaceId]: nextList,
          },
        };
      }

      // CRITICAL FIX: Handle race condition between renameThreadId and subsequent events.
      // If threadId is engine:{sessionId} but not found, check for pending thread to rename.
      const pendingPrefix = action.threadId.startsWith("claude:")
        ? "claude-pending-"
        : action.threadId.startsWith("gemini:")
          ? "gemini-pending-"
        : action.threadId.startsWith("opencode:")
          ? "opencode-pending-"
          : null;
      if (pendingPrefix) {
        const pendingIndexes: number[] = [];
        list.forEach((thread, index) => {
          if (thread.id.startsWith(pendingPrefix)) {
            pendingIndexes.push(index);
          }
        });

        const hasPendingThreadAnchor = (threadId: string) => {
          const hasActiveTurn = (state.activeTurnIdByThread[threadId] ?? null) !== null;
          if (hasActiveTurn) {
            return true;
          }
          const isProcessing = Boolean(state.threadStatusById[threadId]?.isProcessing);
          const hasObservedItems = (state.itemsByThread[threadId]?.length ?? 0) > 0;
          return isProcessing && hasObservedItems;
        };
        const activePendingId = state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
        const resolveActivePendingIndex = (): number | null => {
          if (!activePendingId || !activePendingId.startsWith(pendingPrefix)) {
            return null;
          }
          const activeIndex = pendingIndexes.find(
            (index) => list[index]?.id === activePendingId,
          );
          if (activeIndex === undefined) {
            return null;
          }
          const threadId = list[activeIndex]?.id ?? "";
          if (!threadId || !hasPendingThreadAnchor(threadId)) {
            return null;
          }
          return activeIndex;
        };

        // Boundary first: when multiple pending threads exist for the same engine,
        // never auto-rename here. The incoming finalized session event may belong
        // to any pending stream, and guessing can cross-bind sessions.
        //
        // We rely on explicit thread/session mapping (thread/sessionIdUpdated) to
        // reconcile those cases safely.
        let pendingIndex: number | null = null;
        if (pendingIndexes.length === 1) {
          const singlePendingIndex = pendingIndexes[0];
          const singlePendingId =
            singlePendingIndex !== undefined ? (list[singlePendingIndex]?.id ?? "") : "";
          if (singlePendingId && hasPendingThreadAnchor(singlePendingId)) {
            pendingIndex = singlePendingIndex ?? null;
          }
        } else if (pendingIndexes.length === 0) {
          pendingIndex = resolveActivePendingIndex();
        }

        if (pendingIndex !== null) {
          // Found a pending thread - perform inline rename to avoid race condition
          const pendingThread = list[pendingIndex];
          if (!pendingThread) {
            return state;
          }
          const oldThreadId = pendingThread.id;
          const newThreadId = action.threadId;

          // Rename thread inline (similar to renameThreadId action)
          const updatedThread = { ...pendingThread, id: newThreadId };
          const nextList = [...list];
          nextList[pendingIndex] = updatedThread;

          // Update all related state maps
          const newItemsByThread = { ...state.itemsByThread };
          if (newItemsByThread[oldThreadId]) {
            newItemsByThread[newThreadId] = newItemsByThread[oldThreadId];
            delete newItemsByThread[oldThreadId];
          }

          const newThreadStatusById = { ...state.threadStatusById };
          if (newThreadStatusById[oldThreadId]) {
            newThreadStatusById[newThreadId] = newThreadStatusById[oldThreadId];
            delete newThreadStatusById[oldThreadId];
          }

          const newActiveTurnIdByThread = { ...state.activeTurnIdByThread };
          if (newActiveTurnIdByThread[oldThreadId] !== undefined) {
            newActiveTurnIdByThread[newThreadId] = newActiveTurnIdByThread[oldThreadId];
            delete newActiveTurnIdByThread[oldThreadId];
          }

          const newCodexAcceptedTurnByThread = { ...state.codexAcceptedTurnByThread };
          if (newCodexAcceptedTurnByThread[oldThreadId]) {
            newCodexAcceptedTurnByThread[newThreadId] =
              newCodexAcceptedTurnByThread[oldThreadId];
            delete newCodexAcceptedTurnByThread[oldThreadId];
          }

          const newActiveThreadIdByWorkspace = { ...state.activeThreadIdByWorkspace };
          if (newActiveThreadIdByWorkspace[action.workspaceId] === oldThreadId) {
            newActiveThreadIdByWorkspace[action.workspaceId] = newThreadId;
          }

          const newTokenUsageByThread = { ...state.tokenUsageByThread };
          if (newTokenUsageByThread[oldThreadId]) {
            newTokenUsageByThread[newThreadId] = newTokenUsageByThread[oldThreadId];
            delete newTokenUsageByThread[oldThreadId];
          }

          const newPlanByThread = { ...state.planByThread };
          if (newPlanByThread[oldThreadId] !== undefined) {
            newPlanByThread[newThreadId] = newPlanByThread[oldThreadId];
            delete newPlanByThread[oldThreadId];
          }

          const newLastAgentMessageByThread = { ...state.lastAgentMessageByThread };
          if (newLastAgentMessageByThread[oldThreadId]) {
            newLastAgentMessageByThread[newThreadId] = newLastAgentMessageByThread[oldThreadId];
            delete newLastAgentMessageByThread[oldThreadId];
          }

          const newAgentSegmentByThread = { ...state.agentSegmentByThread };
          if (newAgentSegmentByThread[oldThreadId] !== undefined) {
            newAgentSegmentByThread[newThreadId] = newAgentSegmentByThread[oldThreadId];
            delete newAgentSegmentByThread[oldThreadId];
          }

          const newThreadParentById = { ...state.threadParentById };
          if (newThreadParentById[oldThreadId]) {
            newThreadParentById[newThreadId] = newThreadParentById[oldThreadId];
            delete newThreadParentById[oldThreadId];
          }
          for (const [threadId, parentId] of Object.entries(newThreadParentById)) {
            if (parentId === oldThreadId) {
              newThreadParentById[threadId] = newThreadId;
            }
          }

          return {
            ...state,
            threadsByWorkspace: {
              ...state.threadsByWorkspace,
              [action.workspaceId]: nextList,
            },
            itemsByThread: newItemsByThread,
            threadStatusById: newThreadStatusById,
            activeTurnIdByThread: newActiveTurnIdByThread,
            codexAcceptedTurnByThread: newCodexAcceptedTurnByThread,
            activeThreadIdByWorkspace: newActiveThreadIdByWorkspace,
            tokenUsageByThread: newTokenUsageByThread,
            planByThread: newPlanByThread,
            lastAgentMessageByThread: newLastAgentMessageByThread,
            agentSegmentByThread: newAgentSegmentByThread,
            threadParentById: newThreadParentById,
          };
        }
      }

      // No existing thread and no pending thread to rename - create new thread
      const thread: ThreadSummary = {
        id: action.threadId,
        name: `Agent ${list.length + 1}`,
        updatedAt: 0,
        engineSource: action.engine,
        folderId: action.folderId ?? null,
      };
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: [thread, ...list],
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: withThreadStatusDefaults(),
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]:
            state.activeThreadIdByWorkspace[action.workspaceId] ?? action.threadId,
        },
      };
    }
    case "hideThread": {
      const hiddenForWorkspace =
        state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      if (hiddenForWorkspace[action.threadId]) {
        return state;
      }

      const nextHiddenForWorkspace = {
        ...hiddenForWorkspace,
        [action.threadId]: true as const,
      };

      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;

      return {
        ...state,
        hiddenThreadIdsByWorkspace: {
          ...state.hiddenThreadIdsByWorkspace,
          [action.workspaceId]: nextHiddenForWorkspace,
        },
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "removeThread": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
      const { [action.threadId]: _items, ...restItems } = state.itemsByThread;
      const { [action.threadId]: _historyRestoredAt, ...restHistoryRestoredAt } =
        state.historyRestoredAtMsByThread;
      const { [action.threadId]: _status, ...restStatus } = state.threadStatusById;
      const { [action.threadId]: _turns, ...restTurns } = state.activeTurnIdByThread;
      const { [action.threadId]: _codexAcceptedTurn, ...restCodexAcceptedTurn } =
        state.codexAcceptedTurnByThread;
      const { [action.threadId]: _plans, ...restPlans } = state.planByThread;
      const { [action.threadId]: _parents, ...restParents } = state.threadParentById;
      const { [action.threadId]: _tokenUsage, ...restTokenUsage } = state.tokenUsageByThread;
      const { [action.threadId]: _lastAgent, ...restLastAgent } = state.lastAgentMessageByThread;
      const { [action.threadId]: _segments, ...restSegments } = state.agentSegmentByThread;
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        itemsByThread: restItems,
        historyRestoredAtMsByThread: restHistoryRestoredAt,
        threadStatusById: restStatus,
        activeTurnIdByThread: restTurns,
        codexAcceptedTurnByThread: restCodexAcceptedTurn,
        planByThread: restPlans,
        threadParentById: restParents,
        tokenUsageByThread: restTokenUsage,
        lastAgentMessageByThread: restLastAgent,
        agentSegmentByThread: restSegments,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "evictThreadItems": {
      if (!action.threadIds.length) {
        return state;
      }
      const nextItemsByThread = { ...state.itemsByThread };
      let didChange = false;
      action.threadIds.forEach((threadId) => {
        if (!(threadId in nextItemsByThread)) {
          return;
        }
        delete nextItemsByThread[threadId];
        didChange = true;
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        itemsByThread: nextItemsByThread,
      };
    }
    case "setThreadParent": {
      if (!action.parentId || action.parentId === action.threadId) {
        return state;
      }
      if (state.threadParentById[action.threadId] === action.parentId) {
        return state;
      }
      return {
        ...state,
        threadParentById: {
          ...state.threadParentById,
          [action.threadId]: action.parentId,
        },
      };
    }
    case "markProcessing": {
      const previous = state.threadStatusById[action.threadId];
      const wasProcessing = previous?.isProcessing ?? false;
      const startedAt = previous?.processingStartedAt ?? null;
      const lastDurationMs = previous?.lastDurationMs ?? null;
      const heartbeatPulse = previous?.heartbeatPulse ?? 0;
      const continuationPulse = previous?.continuationPulse ?? 0;
      const terminalPulse = previous?.terminalPulse ?? 0;
      const compactionSource = previous?.codexCompactionSource ?? null;
      const compactionLifecycleState =
        previous?.codexCompactionLifecycleState ?? "idle";
      const compactionCompletedAt =
        previous?.codexCompactionCompletedAt ?? null;
      const lastTokenUsageUpdatedAt =
        previous?.lastTokenUsageUpdatedAt ?? null;
      if (action.isProcessing) {
        if (REDUCER_NOOP_GUARD_ENABLED && wasProcessing) {
          return state;
        }
        return {
          ...state,
          threadStatusById: {
            ...state.threadStatusById,
            [action.threadId]: {
              isProcessing: true,
              hasUnread: previous?.hasUnread ?? false,
              isReviewing: previous?.isReviewing ?? false,
              isContextCompacting: previous?.isContextCompacting ?? false,
              processingStartedAt:
                wasProcessing && startedAt ? startedAt : action.timestamp,
              lastDurationMs,
              heartbeatPulse: wasProcessing ? heartbeatPulse : 0,
              continuationPulse,
              terminalPulse,
              codexCompactionSource: compactionSource,
              codexCompactionLifecycleState: compactionLifecycleState,
              codexCompactionCompletedAt: compactionCompletedAt,
              lastTokenUsageUpdatedAt,
            },
          },
        };
      }
      if (
        REDUCER_NOOP_GUARD_ENABLED &&
        (!previous ||
          (!wasProcessing &&
            previous.processingStartedAt == null &&
            (previous.heartbeatPulse ?? 0) === 0))
      ) {
        return state;
      }
      const nextDuration =
        wasProcessing && startedAt
          ? Math.max(0, action.timestamp - startedAt)
          : lastDurationMs ?? null;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: false,
            hasUnread: previous?.hasUnread ?? false,
            isReviewing: previous?.isReviewing ?? false,
            isContextCompacting: previous?.isContextCompacting ?? false,
            processingStartedAt: null,
            lastDurationMs: nextDuration,
            heartbeatPulse: 0,
            continuationPulse,
            terminalPulse,
            codexCompactionSource: compactionSource,
            codexCompactionLifecycleState: compactionLifecycleState,
            codexCompactionCompletedAt: compactionCompletedAt,
            lastTokenUsageUpdatedAt,
          },
        },
      };
    }
    case "markContextCompacting": {
      const previous = state.threadStatusById[action.threadId];
      const currentIsCompacting = previous?.isContextCompacting ?? false;
      const actionTimestamp =
        typeof action.timestamp === "number" && Number.isFinite(action.timestamp)
          ? action.timestamp
          : null;
      const previousSource = previous?.codexCompactionSource ?? null;
      const previousLifecycleState =
        previous?.codexCompactionLifecycleState ?? "idle";
      const nextLifecycleState: CodexCompactionLifecycleState = action.isCompacting
        ? "compacting"
        : action.completionStatus === "completed"
          ? "completed"
          : previousLifecycleState === "completed"
            ? "completed"
          : "idle";
      const nextSource =
        action.source !== undefined
          ? action.source
          : nextLifecycleState === "completed" &&
              previousLifecycleState !== "idle"
            ? previousSource
            : null;
      if (
        currentIsCompacting === action.isCompacting &&
        previousLifecycleState === nextLifecycleState &&
        previousSource === nextSource
      ) {
        return state;
      }
      const startedAt = previous?.processingStartedAt ?? null;
      const nextStartedAt = action.isCompacting
        ? (startedAt ?? actionTimestamp ?? Date.now())
        : (previous?.isProcessing ?? false ? startedAt : null);
      const nextDuration = !action.isCompacting && currentIsCompacting
        ? (startedAt || actionTimestamp)
          ? Math.max(
              0,
              (actionTimestamp ?? Date.now()) - (startedAt ?? actionTimestamp ?? Date.now()),
            )
          : previous?.lastDurationMs ?? null
        : previous?.lastDurationMs ?? null;
      const nextCompletedAt = nextLifecycleState === "completed"
        ? (actionTimestamp ?? Date.now())
        : null;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: previous?.isProcessing ?? false,
            hasUnread: previous?.hasUnread ?? false,
            isReviewing: previous?.isReviewing ?? false,
            isContextCompacting: action.isCompacting,
            processingStartedAt: nextStartedAt,
            lastDurationMs: nextDuration,
            heartbeatPulse: previous?.heartbeatPulse ?? 0,
            continuationPulse: previous?.continuationPulse ?? 0,
            terminalPulse: previous?.terminalPulse ?? 0,
            codexCompactionSource: nextSource,
            codexCompactionLifecycleState: nextLifecycleState,
            codexCompactionCompletedAt: nextCompletedAt,
            lastTokenUsageUpdatedAt:
              previous?.lastTokenUsageUpdatedAt ?? null,
          },
        },
      };
    }
    case "markHeartbeat": {
      const previous = state.threadStatusById[action.threadId];
      if (!previous?.isProcessing) {
        return state;
      }
      if (action.pulse <= 0 || action.pulse <= (previous.heartbeatPulse ?? 0)) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...previous,
            heartbeatPulse: action.pulse,
          },
        },
      };
    }
    case "markContinuationEvidence": {
      const previous = state.threadStatusById[action.threadId];
      const nextPulse = (previous?.continuationPulse ?? 0) + 1;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(previous),
            continuationPulse: nextPulse,
          },
        },
      };
    }
    case "markTerminalSettlement": {
      const previous = state.threadStatusById[action.threadId];
      const nextPulse = (previous?.terminalPulse ?? 0) + 1;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(previous),
            terminalPulse: nextPulse,
          },
        },
      };
    }
    case "finalizePendingToolStatuses": {
      const list = state.itemsByThread[action.threadId] ?? [];
      let didChange = false;

      const nextItems = list.map((item) => {
        if (item.kind !== "tool") {
          return item;
        }

        if (shouldFinalizeToolStatus(item.status)) {
          didChange = true;
          return {
            ...item,
            status: action.status,
          };
        }

        return item;
      });

      if (!didChange) {
        return state;
      }

      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(nextItems),
        },
      };
    }
    case "setActiveTurnId":
      return {
        ...state,
        activeTurnIdByThread: {
          ...state.activeTurnIdByThread,
          [action.threadId]: action.turnId,
        },
      };
    case "markCodexAcceptedTurn": {
      const previous = state.codexAcceptedTurnByThread[action.threadId];
      if (
        previous?.fact === "accepted" &&
        action.fact !== "accepted"
      ) {
        return state;
      }
      if (
        previous?.fact === action.fact &&
        previous.source === action.source
      ) {
        return state;
      }
      return {
        ...state,
        codexAcceptedTurnByThread: {
          ...state.codexAcceptedTurnByThread,
          [action.threadId]: {
            fact: action.fact,
            source: action.source,
            updatedAt: action.timestamp,
          },
        },
      };
    }
    case "markReviewing":
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(
              state.threadStatusById[action.threadId],
            ),
            isReviewing: action.isReviewing,
          },
        },
      };
    case "markUnread":
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...withThreadStatusDefaults(
              state.threadStatusById[action.threadId],
            ),
            hasUnread: action.hasUnread,
          },
        },
      };
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, message]),
        },
      };
    }
    case "setThreadName": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId ? { ...thread, name: action.name } : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadEngine": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId
          ? {
              ...thread,
              engineSource: action.engine,
              ...(thread.threadKind === "shared"
                ? { selectedEngine: action.engine }
                : {}),
            }
          : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadTimestamp": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (!list.length) {
        return state;
      }
      let didChange = false;
      const next = list.map((thread) => {
        if (thread.id !== action.threadId) {
          return thread;
        }
        const current = thread.updatedAt ?? 0;
        if (current >= action.timestamp) {
          return thread;
        }
        didChange = true;
        return { ...thread, updatedAt: action.timestamp };
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "appendAgentDelta": {
      const segmentedItemId = resolveLiveAssistantMessageId(
        state,
        action.threadId,
        action.itemId,
      );

      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      let index = findAssistantMessageIndexById(list, segmentedItemId);
      let shouldCanonicalizeLegacyId = false;
      if (index < 0 && !isLegacyTextDeltaItemId(action.threadId, segmentedItemId)) {
        const legacySegmentedItemId = resolveLiveAssistantMessageId(
          state,
          action.threadId,
          buildLegacyTextDeltaItemId(action.threadId),
        );
        index = findAssistantMessageIndexById(list, legacySegmentedItemId);
        if (index < 0) {
          index = findAssistantMessageIndexByLegacyTextDelta(list, action.threadId);
        }
        shouldCanonicalizeLegacyId = index >= 0;
      }
      const shouldDeduplicateCodexAssistant = shouldDeduplicateCodexAssistantMessages({
        threadsByWorkspace: state.threadsByWorkspace,
        workspaceId: action.workspaceId,
        threadId: action.threadId,
      });
      if (index < 0 && shouldDeduplicateCodexAssistant) {
        index = findEquivalentCodexAssistantMessageIndex(list, action.delta);
      }
      if (index >= 0) {
        const existing = list[index];
        if (!existing || !isAssistantMessageItem(existing)) {
          return state;
        }
        const isThreadProcessing = Boolean(state.threadStatusById[action.threadId]?.isProcessing);
        const keepFinalMetadata = shouldPreserveAssistantFinalMetadata(
          existing,
          isThreadProcessing,
        );
        const nextId = shouldCanonicalizeLegacyId ? segmentedItemId : existing.id;
        const nextText = mergeAgentMessageText(existing.text, action.delta);
        if (
          INCREMENTAL_DERIVATION_ENABLED &&
          nextId === existing.id &&
          nextText === existing.text
        ) {
          return state;
        }
        const nextBase = keepFinalMetadata
          ? existing
          : clearAssistantFinalMetadata(existing);
        list[index] = {
          ...nextBase,
          id: nextId,
          text: nextText,
          isFinal: keepFinalMetadata ? true : false,
        };
        if (
          canUseLiveAssistantDeltaFastPath({
            threadId: action.threadId,
            list,
            index,
            shouldCanonicalizeLegacyId,
            keepFinalMetadata,
          })
        ) {
          list[index] = normalizeItem(list[index]);
          const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
            workspaceId: action.workspaceId,
            threadId: action.threadId,
            items: list,
            itemId: segmentedItemId,
            hasCustomName: action.hasCustomName,
            threadsByWorkspace: state.threadsByWorkspace,
          });
          return {
            ...state,
            itemsByThread: {
              ...state.itemsByThread,
              [action.threadId]: list,
            },
            threadsByWorkspace: nextThreadsByWorkspace,
          };
        }
      } else {
        list.push({
          id: segmentedItemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
          isFinal: false,
        });
      }
      const updatedItems = prepareThreadItems(list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: segmentedItemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const segmentedItemId = resolveLiveAssistantMessageId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      let index = findAssistantMessageIndexById(list, segmentedItemId);
      if (index < 0) {
        index = findAssistantMessageIndexById(list, action.itemId);
      }
      if (index < 0) {
        index = findAssistantMessageIndexByPrefix(list, action.itemId);
      }
      let shouldCanonicalizeLegacyId = false;
      if (index < 0 && !isLegacyTextDeltaItemId(action.threadId, segmentedItemId)) {
        const legacySegmentedItemId = resolveLiveAssistantMessageId(
          state,
          action.threadId,
          buildLegacyTextDeltaItemId(action.threadId),
        );
        index = findAssistantMessageIndexById(list, legacySegmentedItemId);
        if (index < 0) {
          index = findAssistantMessageIndexByLegacyTextDelta(list, action.threadId);
        }
        shouldCanonicalizeLegacyId = index >= 0;
      }
      const shouldDeduplicateCodexAssistant = shouldDeduplicateCodexAssistantMessages({
        threadsByWorkspace: state.threadsByWorkspace,
        workspaceId: action.workspaceId,
        threadId: action.threadId,
      });
      if (index < 0 && shouldDeduplicateCodexAssistant) {
        index = findEquivalentCodexAssistantMessageIndex(list, action.text);
      }
      const targetItemId =
        index >= 0
          ? shouldCanonicalizeLegacyId
            ? segmentedItemId
            : (list[index]?.id ?? segmentedItemId)
          : segmentedItemId;
      const completedAt = action.timestamp ?? Date.now();
      const status = state.threadStatusById[action.threadId];
      const statusDuration =
        typeof status?.lastDurationMs === "number"
          ? Math.max(0, status.lastDurationMs)
          : null;
      const derivedDuration =
        statusDuration !== null
          ? statusDuration
          : status?.processingStartedAt
            ? Math.max(0, completedAt - status.processingStartedAt)
            : null;
      const existingItem = index >= 0 ? list[index] : undefined;
      if (isAssistantMessageItem(existingItem)) {
        const isThreadProcessing = Boolean(state.threadStatusById[action.threadId]?.isProcessing);
        const keepFinalMetadata = shouldPreserveAssistantFinalMetadata(
          existingItem,
          isThreadProcessing,
        );
        const nextBase = keepFinalMetadata
          ? existingItem
          : clearAssistantFinalMetadata(existingItem);
        list[index] = {
          ...nextBase,
          id: targetItemId,
          text: mergeCompletedAgentText(existingItem.text, action.text),
          isFinal: true,
          finalCompletedAt: nextBase.finalCompletedAt ?? completedAt,
          ...(typeof nextBase.finalDurationMs === "number"
            ? { finalDurationMs: nextBase.finalDurationMs }
            : derivedDuration !== null
              ? { finalDurationMs: derivedDuration }
              : {}),
        };
      } else {
        list.push({
          id: targetItemId,
          kind: "message",
          role: "assistant",
          text: action.text,
          isFinal: true,
          finalCompletedAt: completedAt,
          ...(derivedDuration !== null ? { finalDurationMs: derivedDuration } : {}),
        });
      }
      const updatedItems = prepareThreadItems(list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: targetItemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const isUserMessage = isUserMessageItem(item);
      const isOptimisticUser = isUserMessage && isOptimisticUserMessageId(item.id);
      let generatedImagesToReinsertAfterUser: GeneratedImageItem[] = [];
      if (isUserMessage && !isOptimisticUser) {
        const optimisticReplacement =
          replaceOptimisticUserAndExtractAnchoredGeneratedImages(list, item);
        list = optimisticReplacement.items;
        generatedImagesToReinsertAfterUser =
          optimisticReplacement.generatedImagesToReinsert;
      }
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      let nextItem = ensureUniqueReviewId(list, item);
      if (
        nextItem.kind === "generatedImage" &&
        !isProcessingGeneratedImageItem(nextItem)
      ) {
        const replacedList = replaceMatchingProcessingGeneratedImage(
          list,
          nextItem,
        );
        if (replacedList) {
          return {
            ...state,
            itemsByThread: {
              ...state.itemsByThread,
              [action.threadId]: prepareThreadItems(replacedList),
            },
          };
        }
      }
      if (nextItem.kind === "reasoning") {
        const segmentedReasoningId = resolveLiveReasoningItemId(
          state,
          action.threadId,
          nextItem.id,
        );
        if (segmentedReasoningId !== nextItem.id) {
          nextItem = { ...nextItem, id: segmentedReasoningId };
        }
        const existingReasoning = list.find(
          (entry): entry is Extract<ConversationItem, { kind: "reasoning" }> =>
            entry.id === nextItem.id && entry.kind === "reasoning",
        );
        if (existingReasoning) {
          const existingSummary = normalizeReasoningReadableText(existingReasoning.summary);
          const incomingSummary = normalizeReasoningReadableText(nextItem.summary);
          const existingContent = normalizeReasoningReadableText(existingReasoning.content);
          const incomingContent = normalizeReasoningReadableText(nextItem.content);
          nextItem = {
            ...nextItem,
            summary: mergeReasoningSnapshotTextForThread(
              action.threadId,
              existingSummary,
              incomingSummary,
            ),
            content: mergeReasoningSnapshotTextForThread(
              action.threadId,
              existingContent,
              incomingContent,
            ),
          };
        } else {
          const normalizedIncoming = {
            ...nextItem,
            summary: normalizeReasoningReadableText(nextItem.summary),
            content: normalizeReasoningReadableText(nextItem.content),
          };
          const duplicateIndex = findDuplicateReasoningSnapshotIndex(
            list,
            normalizedIncoming,
          );
          if (
            duplicateIndex >= 0 &&
            list[duplicateIndex]?.kind === "reasoning"
          ) {
            const duplicate = list[duplicateIndex] as Extract<
              ConversationItem,
              { kind: "reasoning" }
            >;
            nextItem = {
              ...normalizedIncoming,
              id: duplicate.id,
              summary: mergeReasoningSnapshotTextForThread(
                action.threadId,
                duplicate.summary,
                normalizedIncoming.summary,
              ),
              content: mergeReasoningSnapshotTextForThread(
                action.threadId,
                duplicate.content,
                normalizedIncoming.content,
              ),
            };
          } else {
            nextItem = normalizedIncoming;
          }
        }
      }
      if (
        nextItem.kind === "message" &&
        nextItem.role === "assistant" &&
        shouldDeduplicateCodexAssistantMessages({
          threadsByWorkspace: state.threadsByWorkspace,
          workspaceId: action.workspaceId,
          threadId: action.threadId,
        }) &&
        findAssistantMessageIndexById(list, nextItem.id) < 0
      ) {
        const equivalentAssistantIndex = findEquivalentCodexAssistantMessageIndex(
          list,
          nextItem.text,
        );
        const equivalentAssistant =
          equivalentAssistantIndex >= 0 ? list[equivalentAssistantIndex] : undefined;
        if (isAssistantMessageItem(equivalentAssistant)) {
          const mergedText = mergeAgentMessageText(
            equivalentAssistant.text,
            nextItem.text,
          );
          list = [
            ...list.slice(0, equivalentAssistantIndex),
            {
              ...equivalentAssistant,
              ...nextItem,
              id: equivalentAssistant.id,
              text: mergedText,
            },
            ...list.slice(equivalentAssistantIndex + 1),
          ];
          nextItem = list[equivalentAssistantIndex] ?? nextItem;
        }
      }
      let nextList = upsertItem(list, nextItem);
      if (generatedImagesToReinsertAfterUser.length > 0) {
        nextList = insertGeneratedImagesAfterAnchors(
          nextList,
          generatedImagesToReinsertAfterUser,
        );
      }
      const updatedItems = prepareThreadItems(nextList);
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName = shouldRename ? textValue : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads = updatedThreads.length
          ? [
              ...updatedThreads.filter((thread) => thread.id === action.threadId),
              ...updatedThreads.filter((thread) => thread.id !== action.threadId),
            ]
          : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "applyNormalizedRealtimeEvent":
      return reduceNormalizedRealtimeEvent(
        state,
        action,
        maybeRenameThreadFromAgent,
      );
    case "clearProcessingGeneratedImages": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const filtered = list.filter(
        (item) => !isProcessingGeneratedImageItem(item),
      );
      if (filtered.length === list.length) {
        return state;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(filtered),
        },
      };
    }
    case "setThreadItems": {
      const localItems = state.itemsByThread[action.threadId] ?? [];
      const mergedItems = mergeThreadItemsPreservingOptimisticUsers(
        localItems,
        action.items,
        {
          isProcessing: Boolean(state.threadStatusById[action.threadId]?.isProcessing),
          codexCompactionLifecycleState:
            state.threadStatusById[action.threadId]?.codexCompactionLifecycleState ??
            "idle",
        },
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(mergedItems),
        },
      };
    }
    case "setThreadHistoryRestoredAt": {
      const previousTimestamp =
        state.historyRestoredAtMsByThread[action.threadId] ?? null;
      if (previousTimestamp === action.timestamp) {
        return state;
      }
      return {
        ...state,
        historyRestoredAtMsByThread: {
          ...state.historyRestoredAtMsByThread,
          [action.threadId]: action.timestamp,
        },
      };
    }
    case "markLatestAssistantMessageFinal": {
      const list = state.itemsByThread[action.threadId] ?? [];
      if (list.length === 0) {
        return state;
      }
      let latestAssistantIndex = -1;
      for (let index = list.length - 1; index >= 0; index -= 1) {
        const item = list[index];
        if (isAssistantMessageItem(item)) {
          latestAssistantIndex = index;
          break;
        }
      }
      if (latestAssistantIndex < 0) {
        return state;
      }
      const latestAssistant = list[latestAssistantIndex];
      if (!isAssistantMessageItem(latestAssistant)) {
        return state;
      }
      const completedAt =
        latestAssistant.finalCompletedAt ??
        Date.now();
      const status = state.threadStatusById[action.threadId];
      const statusDuration =
        typeof status?.lastDurationMs === "number"
          ? Math.max(0, status.lastDurationMs)
          : null;
      const derivedDuration =
        statusDuration !== null
          ? statusDuration
          : status?.processingStartedAt
            ? Math.max(0, completedAt - status.processingStartedAt)
            : null;
      const durationMs =
        typeof latestAssistant.finalDurationMs === "number"
          ? Math.max(0, latestAssistant.finalDurationMs)
          : derivedDuration;
      const shouldUpdate =
        latestAssistant.isFinal !== true ||
        latestAssistant.finalCompletedAt !== completedAt ||
        latestAssistant.finalDurationMs !== durationMs;
      if (!shouldUpdate) {
        return state;
      }
      const next = [...list];
      next[latestAssistantIndex] = {
        ...latestAssistant,
        isFinal: true,
        finalCompletedAt: completedAt,
        ...(durationMs !== null ? { finalDurationMs: durationMs } : {}),
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "setLastAgentMessage":
      if (
        state.lastAgentMessageByThread[action.threadId] &&
        state.lastAgentMessageByThread[action.threadId]!.timestamp >= action.timestamp
      ) {
        return state;
      }
      return {
        ...state,
        lastAgentMessageByThread: {
          ...state.lastAgentMessageByThread,
          [action.threadId]: { text: action.text, timestamp: action.timestamp },
        },
      };
    case "renameThreadId": {
      const { workspaceId, oldThreadId, newThreadId } = action;
      if (oldThreadId === newThreadId) {
        return state;
      }

      // Update activeThreadIdByWorkspace
      const newActiveThreadIdByWorkspace = { ...state.activeThreadIdByWorkspace };
      if (newActiveThreadIdByWorkspace[workspaceId] === oldThreadId) {
        newActiveThreadIdByWorkspace[workspaceId] = newThreadId;
      }

      // Update itemsByThread
      const newItemsByThread = { ...state.itemsByThread };
      if (newItemsByThread[oldThreadId]) {
        const oldItems = newItemsByThread[oldThreadId] ?? [];
        const existingItems = newItemsByThread[newThreadId] ?? [];
        const oldHasUserMessage = oldItems.some(
          (item) => item.kind === "message" && item.role === "user",
        );
        const existingHasUserMessage = existingItems.some(
          (item) => item.kind === "message" && item.role === "user",
        );
        // If existing thread already has user history, append pending items to the tail
        // so the latest user prompt is not truncated out by MAX_ITEMS_PER_THREAD.
        // If existing thread only has assistant deltas (rename race), keep user-first order.
        const mergedItems =
          oldHasUserMessage && !existingHasUserMessage
            ? [...oldItems, ...existingItems]
            : [...existingItems, ...oldItems];
        newItemsByThread[newThreadId] = prepareThreadItems([
          ...mergedItems,
        ]);
        delete newItemsByThread[oldThreadId];
      }

      const newHistoryRestoredAtMsByThread = { ...state.historyRestoredAtMsByThread };
      if (newHistoryRestoredAtMsByThread[oldThreadId] !== undefined) {
        newHistoryRestoredAtMsByThread[newThreadId] =
          newHistoryRestoredAtMsByThread[newThreadId]
          ?? newHistoryRestoredAtMsByThread[oldThreadId]
          ?? null;
        delete newHistoryRestoredAtMsByThread[oldThreadId];
      }

      // Update threadsByWorkspace
      const newThreadsByWorkspace = { ...state.threadsByWorkspace };
      const workspaceThreads = newThreadsByWorkspace[workspaceId];
      if (workspaceThreads) {
        const renamedThreads = workspaceThreads.map((thread) =>
          thread.id === oldThreadId ? { ...thread, id: newThreadId } : thread,
        );
        const dedupedById = new Map<string, ThreadSummary>();
        for (const thread of renamedThreads) {
          const current = dedupedById.get(thread.id);
          if (!current) {
            dedupedById.set(thread.id, thread);
            continue;
          }
          dedupedById.set(thread.id, {
            ...current,
            ...thread,
            updatedAt: Math.max(current.updatedAt, thread.updatedAt),
          });
        }
        newThreadsByWorkspace[workspaceId] = Array.from(dedupedById.values());
      }

      // Update threadStatusById
      const newThreadStatusById = { ...state.threadStatusById };
      if (newThreadStatusById[oldThreadId]) {
        const oldStatus = newThreadStatusById[oldThreadId];
        const existingStatus = newThreadStatusById[newThreadId];
        newThreadStatusById[newThreadId] = existingStatus
          ? {
              isProcessing: oldStatus.isProcessing || existingStatus.isProcessing,
              hasUnread: oldStatus.hasUnread || existingStatus.hasUnread,
              isReviewing: oldStatus.isReviewing || existingStatus.isReviewing,
              isContextCompacting:
                (oldStatus.isContextCompacting ?? false)
                || (existingStatus.isContextCompacting ?? false),
              processingStartedAt:
                oldStatus.processingStartedAt ?? existingStatus.processingStartedAt,
              lastDurationMs:
                oldStatus.lastDurationMs ?? existingStatus.lastDurationMs,
              heartbeatPulse:
                oldStatus.heartbeatPulse ?? existingStatus.heartbeatPulse ?? 0,
              continuationPulse:
                oldStatus.continuationPulse
                ?? existingStatus.continuationPulse
                ?? 0,
              terminalPulse:
                oldStatus.terminalPulse ?? existingStatus.terminalPulse ?? 0,
              codexCompactionSource:
                oldStatus.codexCompactionLifecycleState !== "idle"
                  ? (oldStatus.codexCompactionSource ?? null)
                  : (existingStatus.codexCompactionSource ?? null),
              codexCompactionLifecycleState:
                oldStatus.codexCompactionLifecycleState !== "idle"
                  ? (oldStatus.codexCompactionLifecycleState ?? "idle")
                  : (existingStatus.codexCompactionLifecycleState ?? "idle"),
              codexCompactionCompletedAt:
                oldStatus.codexCompactionCompletedAt
                ?? existingStatus.codexCompactionCompletedAt
                ?? null,
              lastTokenUsageUpdatedAt:
                oldStatus.lastTokenUsageUpdatedAt
                ?? existingStatus.lastTokenUsageUpdatedAt
                ?? null,
            }
          : oldStatus;
        delete newThreadStatusById[oldThreadId];
      }

      // Update activeTurnIdByThread
      const newActiveTurnIdByThread = { ...state.activeTurnIdByThread };
      if (newActiveTurnIdByThread[oldThreadId] !== undefined) {
        newActiveTurnIdByThread[newThreadId] =
          newActiveTurnIdByThread[oldThreadId] ??
          newActiveTurnIdByThread[newThreadId] ??
          null;
        delete newActiveTurnIdByThread[oldThreadId];
      }

      const newCodexAcceptedTurnByThread = { ...state.codexAcceptedTurnByThread };
      if (newCodexAcceptedTurnByThread[oldThreadId]) {
        const oldFact = newCodexAcceptedTurnByThread[oldThreadId];
        const existingFact = newCodexAcceptedTurnByThread[newThreadId];
        newCodexAcceptedTurnByThread[newThreadId] =
          existingFact?.fact === "accepted"
            ? existingFact
            : oldFact;
        delete newCodexAcceptedTurnByThread[oldThreadId];
      }

      // Update tokenUsageByThread
      const newTokenUsageByThread = { ...state.tokenUsageByThread };
      if (newTokenUsageByThread[oldThreadId]) {
        newTokenUsageByThread[newThreadId] =
          newTokenUsageByThread[newThreadId] ?? newTokenUsageByThread[oldThreadId];
        delete newTokenUsageByThread[oldThreadId];
      }

      // Update planByThread
      const newPlanByThread = { ...state.planByThread };
      if (newPlanByThread[oldThreadId] !== undefined) {
        newPlanByThread[newThreadId] =
          newPlanByThread[newThreadId] ?? newPlanByThread[oldThreadId];
        delete newPlanByThread[oldThreadId];
      }

      // Update lastAgentMessageByThread
      const newLastAgentMessageByThread = { ...state.lastAgentMessageByThread };
      if (newLastAgentMessageByThread[oldThreadId]) {
        const oldMessage = newLastAgentMessageByThread[oldThreadId];
        const existingMessage = newLastAgentMessageByThread[newThreadId];
        newLastAgentMessageByThread[newThreadId] =
          existingMessage && existingMessage.timestamp > oldMessage.timestamp
            ? existingMessage
            : oldMessage;
        delete newLastAgentMessageByThread[oldThreadId];
      }

      // Update agentSegmentByThread
      const newAgentSegmentByThread = { ...state.agentSegmentByThread };
      if (newAgentSegmentByThread[oldThreadId] !== undefined) {
        newAgentSegmentByThread[newThreadId] = Math.max(
          newAgentSegmentByThread[oldThreadId] ?? 0,
          newAgentSegmentByThread[newThreadId] ?? 0,
        );
        delete newAgentSegmentByThread[oldThreadId];
      }

      // Update threadParentById
      const newThreadParentById = { ...state.threadParentById };
      if (newThreadParentById[oldThreadId]) {
        newThreadParentById[newThreadId] = newThreadParentById[oldThreadId];
        delete newThreadParentById[oldThreadId];
      }
      // Also update any threads that have oldThreadId as parent
      for (const [threadId, parentId] of Object.entries(newThreadParentById)) {
        if (parentId === oldThreadId) {
          newThreadParentById[threadId] = newThreadId;
        }
      }

      // Update hiddenThreadIdsByWorkspace
      const newHiddenThreadIdsByWorkspace = { ...state.hiddenThreadIdsByWorkspace };
      const workspaceHidden = newHiddenThreadIdsByWorkspace[workspaceId];
      if (workspaceHidden?.[oldThreadId]) {
        newHiddenThreadIdsByWorkspace[workspaceId] = {
          ...workspaceHidden,
          [newThreadId]: true,
        };
        delete newHiddenThreadIdsByWorkspace[workspaceId][oldThreadId];
      }
      const newUserInputRequests = state.userInputRequests.map((request) => {
        if (
          request.workspace_id !== workspaceId ||
          request.params.thread_id !== oldThreadId
        ) {
          return request;
        }
        return {
          ...request,
          params: {
            ...request.params,
            thread_id: newThreadId,
          },
        };
      });

      return {
        ...state,
        activeThreadIdByWorkspace: newActiveThreadIdByWorkspace,
        itemsByThread: newItemsByThread,
        historyRestoredAtMsByThread: newHistoryRestoredAtMsByThread,
        threadsByWorkspace: newThreadsByWorkspace,
        threadStatusById: newThreadStatusById,
        activeTurnIdByThread: newActiveTurnIdByThread,
        codexAcceptedTurnByThread: newCodexAcceptedTurnByThread,
        tokenUsageByThread: newTokenUsageByThread,
        planByThread: newPlanByThread,
        lastAgentMessageByThread: newLastAgentMessageByThread,
        agentSegmentByThread: newAgentSegmentByThread,
        threadParentById: newThreadParentById,
        hiddenThreadIdsByWorkspace: newHiddenThreadIdsByWorkspace,
        userInputRequests: newUserInputRequests,
      };
    }
    case "appendReasoningSummary": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = mergeReasoningTextForThread(
        action.threadId,
        "summary" in base ? base.summary : "",
        action.delta,
      );
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "summary" in base &&
        nextSummary === base.summary
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      if (INCREMENTAL_DERIVATION_ENABLED && index >= 0) {
        const next = [...list];
        next[index] = normalizeItem(updated);
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = addSummaryBoundary("summary" in base ? base.summary : "");
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "summary" in base &&
        nextSummary === base.summary
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      if (INCREMENTAL_DERIVATION_ENABLED && index >= 0) {
        const next = [...list];
        next[index] = normalizeItem(updated);
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendContextCompacted": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const id = `context-compacted-${action.turnId}`;
      if (list.some((entry) => entry.id === id)) {
        return state;
      }
      const compactedMessage: ConversationItem = {
        id,
        kind: "message",
        role: "assistant",
        text: "Context compacted.",
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, compactedMessage]),
        },
      };
    }
    case "settleCodexCompactionMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const fallbackMessageId = action.fallbackMessageId ?? null;
      if (action.appendIfAlreadyCompleted) {
        if (!fallbackMessageId || list.some((entry) => entry.id === fallbackMessageId)) {
          return state;
        }
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: prepareThreadItems([
              ...list,
              buildCodexCompactionMessage(action.threadId, action.text, fallbackMessageId),
            ]),
          },
        };
      }
      const { latestMatch, matchCount } = collectThreadScopedCodexCompactionMessages(
        list,
        action.threadId,
      );
      if (latestMatch?.text === action.text && matchCount === 1) {
        return state;
      }
      const next = [
        ...filterThreadScopedCodexCompactionMessages(list, action.threadId),
        buildCodexCompactionMessage(
          action.threadId,
          action.text,
          latestMatch?.id ?? fallbackMessageId ?? undefined,
        ),
      ];
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendCodexCompactionMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const lastItem = list[list.length - 1];
      const { latestMatch, matchCount } = collectThreadScopedCodexCompactionMessages(
        list,
        action.threadId,
      );
      const shouldReuseLatestStartedMessage =
        isThreadScopedCodexCompactionMessage(lastItem, action.threadId) &&
        latestMatch?.text === action.text &&
        !latestMatch.id.includes("-completed-");
      if (shouldReuseLatestStartedMessage && matchCount === 1) {
        return state;
      }
      const next = [
        ...filterThreadScopedCodexCompactionMessages(list, action.threadId),
        shouldReuseLatestStartedMessage
          ? latestMatch
          : buildCodexCompactionMessage(action.threadId, action.text),
      ];
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "discardLatestCodexCompactionMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      let existingIndex = -1;
      for (let index = list.length - 1; index >= 0; index -= 1) {
        if (isThreadScopedCodexCompactionMessage(list[index], action.threadId)) {
          existingIndex = index;
          break;
        }
      }
      if (existingIndex < 0) {
        return state;
      }
      const existingItem = list[existingIndex];
      if (
        !isThreadScopedCodexCompactionMessage(existingItem, action.threadId) ||
        existingItem.text !== action.text
      ) {
        return state;
      }
      const next = list.filter((_, index) => index !== existingIndex);
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningContent": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextContent = mergeReasoningTextForThread(
        action.threadId,
        "content" in base ? base.content : "",
        action.delta,
      );
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "content" in base &&
        nextContent === base.content
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        content: nextContent,
      } as ConversationItem;
      if (INCREMENTAL_DERIVATION_ENABLED && index >= 0) {
        const next = [...list];
        next[index] = normalizeItem(updated);
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "dropReasoningItems": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const filtered = list.filter((item) => item.kind !== "reasoning");
      if (filtered.length === list.length) {
        return state;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(filtered),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0) {
        const placeholder: ConversationItem = {
          id: action.itemId,
          kind: "tool",
          toolType: "commandExecution",
          title: "Command",
          detail: "",
          status: "running",
          output: action.delta,
        };
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: prepareThreadItems([...list, placeholder]),
          },
        };
      }
      const existing = list[index];
      if (!isToolConversationItem(existing)) {
        return state;
      }
      const nextOutput = mergeStreamingText(existing.output ?? "", action.delta);
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        nextOutput === (existing.output ?? "")
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...existing,
        output: nextOutput,
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      if (INCREMENTAL_DERIVATION_ENABLED) {
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: next,
          },
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "addApproval": {
      const exists = state.approvals.some(
        (item) => isSameApprovalRequest(item, action.approval),
      );
      if (exists) {
        return state;
      }
      return { ...state, approvals: [...state.approvals, action.approval] };
    }
    case "removeApproval":
      return {
        ...state,
        approvals: state.approvals.filter(
          (item) =>
            action.approval
              ? !isSameApprovalRequest(item, action.approval)
              : item.request_id !== action.requestId ||
                item.workspace_id !== action.workspaceId,
        ),
      };
    case "addUserInputRequest": {
      const exists = state.userInputRequests.some(
        (item) =>
          item.request_id === action.request.request_id &&
          item.workspace_id === action.request.workspace_id,
      );
      if (exists) {
        return state;
      }
      return {
        ...state,
        userInputRequests: [...state.userInputRequests, action.request],
      };
    }
    case "removeUserInputRequest":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.request_id !== action.requestId ||
            item.workspace_id !== action.workspaceId,
        ),
      };
    case "clearUserInputRequestsForThread":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.workspace_id !== action.workspaceId ||
            item.params.thread_id !== action.threadId,
        ),
      };
    case "setThreads": {
      const hidden = state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      const existingThreads = state.threadsByWorkspace[action.workspaceId] ?? [];
      const now = Date.now();
      const shouldPreserveDegradedCodexFinalizedThreads = action.threads.some(
        (thread) => thread.isDegraded,
      );
      // BUG FIX: Preserve engineSource and other info from existing threads when merging
      // This prevents loss of explicitly set engine types (e.g., Claude) when refreshing thread list
      const existingThreadById = new Map(
        existingThreads.map((thread) => [thread.id, thread]),
      );
      const newThreadIds = new Set(action.threads.map((thread) => thread.id));
      const hasPendingThreadAnchor = (threadId: string) => {
        const hasActiveTurn = (state.activeTurnIdByThread[threadId] ?? null) !== null;
        if (hasActiveTurn) {
          return true;
        }
        const itemCount = state.itemsByThread[threadId]?.length ?? 0;
        const isProcessing = Boolean(state.threadStatusById[threadId]?.isProcessing);
        if (isProcessing && itemCount > 0) {
          return true;
        }
        const lastAgentMessageTimestamp =
          state.lastAgentMessageByThread[threadId]?.timestamp ?? 0;
        const hasRecentAgentMessage =
          lastAgentMessageTimestamp > 0 &&
          now - lastAgentMessageTimestamp <= PENDING_THREAD_LAST_AGENT_ANCHOR_TTL_MS;
        if (hasRecentAgentMessage) {
          return true;
        }
        return state.userInputRequests.some(
          (request) =>
            request.workspace_id === action.workspaceId
            && request.params.thread_id === threadId,
        );
      };

      // Merge incoming threads with preserved existing info
      const visibleThreads = action.threads
        .filter((thread) => !hidden[thread.id])
        .map((thread) => {
          const existing = existingThreadById.get(thread.id);
          if (existing) {
            // Preserve engineSource if new thread doesn't have one
            const engineSource = thread.engineSource || existing.engineSource;
            const threadKind = thread.threadKind || existing.threadKind;
            const selectedEngine = thread.selectedEngine || existing.selectedEngine;
            const nativeThreadIds = thread.nativeThreadIds || existing.nativeThreadIds;
            const name = shouldPreferExistingThreadName(existing.name, thread.name)
              ? existing.name
              : thread.name;
            return { ...thread, name, engineSource, threadKind, selectedEngine, nativeThreadIds };
          }
          return thread;
        });

      // BUG FIX: Also preserve threads that are currently active but not in the new list
      // (e.g., newly created Claude threads that haven't been synced to the backend yet)
      const activeThreadId = state.activeThreadIdByWorkspace[action.workspaceId];
      if (activeThreadId) {
        const activeThread = existingThreadById.get(activeThreadId);
        if (activeThread && !newThreadIds.has(activeThreadId) && !hidden[activeThreadId]) {
          // Prepend the active thread to preserve it
          visibleThreads.unshift(activeThread);
        }
      }

      // Preserve non-active pending threads that are still anchored by realtime state.
      // Without this, background CLI sessions can briefly appear as pending and then
      // disappear on the next list refresh before local history indexing catches up.
      const preservedThreadIds = new Set(visibleThreads.map((thread) => thread.id));
      const pendingToPreserve = existingThreads.filter((thread) => {
        const threadId = thread.id;
        if (!threadId.includes("-pending-")) {
          return false;
        }
        if (threadId === activeThreadId) {
          return false;
        }
        if (hidden[threadId] || newThreadIds.has(threadId) || preservedThreadIds.has(threadId)) {
          return false;
        }
        if (typeof thread.folderId === "string" && thread.folderId.trim().length > 0) {
          return true;
        }
        return hasPendingThreadAnchor(threadId);
      });
      pendingToPreserve.forEach((thread) => preservedThreadIds.add(thread.id));
      const finalizedCodexToPreserve = shouldPreserveDegradedCodexFinalizedThreads
        ? existingThreads.filter((thread) => {
          const threadId = thread.id;
          if (
            !isRetainableFinalizedCodexThread(thread)
            || threadId === activeThreadId
            || hidden[threadId]
            || newThreadIds.has(threadId)
            || preservedThreadIds.has(threadId)
          ) {
            return false;
          }
          return true;
        })
        : [];
      finalizedCodexToPreserve.forEach((thread) => preservedThreadIds.add(thread.id));
      const mergedVisibleThreads =
        pendingToPreserve.length > 0 || finalizedCodexToPreserve.length > 0
          ? activeThreadId && visibleThreads[0]?.id === activeThreadId
            ? [
              visibleThreads[0],
              ...finalizedCodexToPreserve,
              ...pendingToPreserve,
              ...visibleThreads.slice(1),
            ]
            : [...finalizedCodexToPreserve, ...pendingToPreserve, ...visibleThreads]
          : visibleThreads;

      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: mergedVisibleThreads,
        },
      };
    }
    case "setThreadListLoading":
      return {
        ...state,
        threadListLoadingByWorkspace: {
          ...state.threadListLoadingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListPaging":
      return {
        ...state,
        threadListPagingByWorkspace: {
          ...state.threadListPagingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListCursor":
      return {
        ...state,
        threadListCursorByWorkspace: {
          ...state.threadListCursorByWorkspace,
          [action.workspaceId]: action.cursor,
        },
      };
    case "setThreadTokenUsage": {
      const existingStatus = withThreadStatusDefaults(
        state.threadStatusById[action.threadId],
      );
      const previousTokenUsage = state.tokenUsageByThread[action.threadId] ?? null;
      const usageSnapshotChanged = !isThreadTokenUsageEqual(
        previousTokenUsage,
        action.tokenUsage,
      );
      const shouldClearCompletedCompaction =
        existingStatus.codexCompactionLifecycleState === "completed" &&
        usageSnapshotChanged;
      if (!usageSnapshotChanged && !shouldClearCompletedCompaction) {
        return state;
      }
      const tokenUsageUpdatedAt = usageSnapshotChanged
        ? Date.now()
        : existingStatus.lastTokenUsageUpdatedAt;
      return {
        ...state,
        tokenUsageByThread: {
          ...state.tokenUsageByThread,
          [action.threadId]: action.tokenUsage,
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...existingStatus,
            codexCompactionLifecycleState: shouldClearCompletedCompaction
              ? "idle"
              : existingStatus.codexCompactionLifecycleState,
            codexCompactionSource: shouldClearCompletedCompaction
              ? null
              : existingStatus.codexCompactionSource,
            codexCompactionCompletedAt: shouldClearCompletedCompaction
              ? null
              : existingStatus.codexCompactionCompletedAt,
            lastTokenUsageUpdatedAt: tokenUsageUpdatedAt,
          },
        },
      };
    }
    case "setRateLimits":
      return {
        ...state,
        rateLimitsByWorkspace: {
          ...state.rateLimitsByWorkspace,
          [action.workspaceId]: action.rateLimits,
        },
      };
    case "setAccountInfo":
      return {
        ...state,
        accountByWorkspace: {
          ...state.accountByWorkspace,
          [action.workspaceId]: action.account,
        },
      };
    case "setThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: action.plan,
        },
      };
    case "settleThreadPlanInProgress": {
      const current = state.planByThread[action.threadId] ?? null;
      const next = settlePlanInProgressSteps(current, action.targetStatus);
      if (next === current) {
        return state;
      }
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: next,
        },
      };
    }
    case "clearThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: null,
        },
      };
    case "incrementAgentSegment": {
      // 当 tool item 开始时调用，增加分段计数，确保后续文本创建新的 message
      const current = state.agentSegmentByThread[action.threadId] ?? 0;
      return {
        ...state,
        agentSegmentByThread: {
          ...state.agentSegmentByThread,
          [action.threadId]: current + 1,
        },
      };
    }
    case "resetAgentSegment":
      // 当 turn 完成时调用，重置分段计数
      return {
        ...state,
        agentSegmentByThread: {
          ...state.agentSegmentByThread,
          [action.threadId]: 0,
        },
      };
    default:
      return state;
  }
}
