import type {
  AccountSnapshot,
  ApprovalRequest,
  ConversationItem,
  RateLimitSnapshot,
  RequestUserInputRequest,
  ThreadSummary,
  ThreadTokenUsage,
  TurnPlan,
} from "../../../types";
import {
  normalizeItem,
  prepareThreadItems,
  previewThreadName,
  upsertItem,
} from "../../../utils/threadItems";
import { settlePlanInProgressSteps } from "../utils/threadNormalize";
import {
  isIncrementalDerivationEnabled,
  isReducerNoopGuardEnabled,
} from "../utils/realtimePerfFlags";
import {
  buildLegacyTextDeltaItemId,
  findAssistantMessageIndexByLegacyTextDelta,
  findReasoningIndexById,
  insertLiveReasoningItem,
  isLegacyTextDeltaItemId,
} from "./threadReducerItemLookup";
import {
  isGeminiReasoningThread,
  isLocalCliReasoningThread,
  shouldAcceptReasoningDelta,
} from "./threadReducerReasoningGuards";
import {
  addSummaryBoundary,
  findDuplicateReasoningSnapshotIndex,
  mergeAgentMessageText,
  mergeCompletedAgentText,
  mergeReasoningSnapshotTextForThread,
  mergeReasoningTextForThread,
  mergeStreamingText,
  normalizeReasoningReadableText,
} from "./threadReducerTextMerge";

const REDUCER_NOOP_GUARD_ENABLED = isReducerNoopGuardEnabled();
const INCREMENTAL_DERIVATION_ENABLED = isIncrementalDerivationEnabled();
const PENDING_THREAD_LAST_AGENT_ANCHOR_TTL_MS = 5 * 60 * 1000;

function formatThreadName(text: string) {
  const trimmed = text.trim();
  if (!trimmed) {
    return null;
  }
  return trimmed;
}

function looksAutoGeneratedThreadName(name: string) {
  return name.startsWith("Agent ") || /^[a-f0-9]{4,8}$/i.test(name);
}

function extractRenameText(text: string) {
  if (!text) {
    return "";
  }
  const withoutImages = text.replace(/\[image(?: x\d+)?\]/gi, " ");
  const withoutSkills = withoutImages.replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ");
  return previewThreadName(withoutSkills, "");
}

const OPTIMISTIC_USER_ITEM_PREFIX = "optimistic-user-";

type MessageItem = Extract<ConversationItem, { kind: "message" }>;
type UserMessageItem = MessageItem & { role: "user" };
type AssistantMessageItem = MessageItem & { role: "assistant" };
type ToolConversationItem = Extract<ConversationItem, { kind: "tool" }>;

function isUserMessageItem(item: ConversationItem | undefined): item is UserMessageItem {
  return item?.kind === "message" && item.role === "user";
}

function isAssistantMessageItem(item: ConversationItem | undefined): item is AssistantMessageItem {
  return item?.kind === "message" && item.role === "assistant";
}

function isToolConversationItem(item: ConversationItem | undefined): item is ToolConversationItem {
  return item?.kind === "tool";
}

function isOptimisticUserMessage(
  item: ConversationItem,
): item is UserMessageItem {
  return isUserMessageItem(item) && item.id.startsWith(OPTIMISTIC_USER_ITEM_PREFIX);
}

function normalizeComparableUserText(text: string) {
  return text.replace(/\s+/g, " ").trim();
}

function normalizeUserImages(images: string[] | undefined) {
  return Array.isArray(images) ? images : [];
}

function areSameUserImages(left: string[], right: string[]) {
  if (left.length !== right.length) {
    return false;
  }
  return left.every((image, index) => image === right[index]);
}

function dropMatchingOptimisticUserMessage(
  list: ConversationItem[],
  incoming: UserMessageItem,
) {
  let matchedIndex = -1;
  let fallbackIndex = -1;
  const incomingText = normalizeComparableUserText(incoming.text);
  const incomingImages = normalizeUserImages(incoming.images);
  for (let index = 0; index < list.length; index += 1) {
    const item = list[index];
    if (!item) {
      continue;
    }
    if (!isOptimisticUserMessage(item)) {
      continue;
    }
    if (fallbackIndex < 0) {
      fallbackIndex = index;
    }
    const textMatches = normalizeComparableUserText(item.text) === incomingText;
    const imageMatches = areSameUserImages(
      normalizeUserImages(item.images),
      incomingImages,
    );
    if (textMatches && imageMatches) {
      matchedIndex = index;
      break;
    }
  }
  const targetIndex = matchedIndex >= 0 ? matchedIndex : fallbackIndex;
  if (targetIndex < 0) {
    return list;
  }
  return [...list.slice(0, targetIndex), ...list.slice(targetIndex + 1)];
}

function findMatchingRealUserMessage(
  list: ConversationItem[],
  candidate: UserMessageItem,
) {
  const candidateText = normalizeComparableUserText(candidate.text);
  const candidateImages = normalizeUserImages(candidate.images);
  return list.some((item) => {
    if (!isUserMessageItem(item)) {
      return false;
    }
    if (item.id.startsWith(OPTIMISTIC_USER_ITEM_PREFIX)) {
      return false;
    }
    return (
      normalizeComparableUserText(item.text) === candidateText &&
      areSameUserImages(normalizeUserImages(item.images), candidateImages)
    );
  });
}

function mergeThreadItemsPreservingOptimisticUsers(
  localItems: ConversationItem[],
  incomingItems: ConversationItem[],
  isProcessing: boolean,
) {
  const hasSelectedAgentName = (value: unknown) =>
    typeof value === "string" && value.trim().length > 0;
  const hasSelectedAgentIcon = (value: unknown) =>
    typeof value === "string" && value.trim().length > 0;
  const hasSelectedAgentMetadata = (item: UserMessageItem) =>
    hasSelectedAgentName(item.selectedAgentName) ||
    hasSelectedAgentIcon(item.selectedAgentIcon);
  const toComparableUserMessageKey = (item: UserMessageItem) => {
    const text = normalizeComparableUserText(item.text);
    const images = normalizeUserImages(item.images).join("\u0001");
    return `${text}\u0000${images}`;
  };
  const toComparableUserMessageSequence = (items: ConversationItem[]) =>
    items
      .filter(isUserMessageItem)
      .map((item) => toComparableUserMessageKey(item));
  const areSameSequence = (left: string[], right: string[]) => {
    if (left.length !== right.length) {
      return false;
    }
    return left.every((value, index) => value === right[index]);
  };
  const localUserSequence = toComparableUserMessageSequence(localItems);
  const incomingUserSequence = toComparableUserMessageSequence(incomingItems);
  const hasUserSequenceDrift = !areSameSequence(localUserSequence, incomingUserSequence);
  const localUserMessageMetadataBuckets = new Map<
    string,
    Array<Pick<UserMessageItem, "selectedAgentName" | "selectedAgentIcon">>
  >();
  for (const item of localItems) {
    if (!isUserMessageItem(item) || !hasSelectedAgentMetadata(item)) {
      continue;
    }
    const key = toComparableUserMessageKey(item);
    const bucket = localUserMessageMetadataBuckets.get(key) ?? [];
    bucket.push({
      selectedAgentName: item.selectedAgentName ?? null,
      selectedAgentIcon: item.selectedAgentIcon ?? null,
    });
    localUserMessageMetadataBuckets.set(key, bucket);
  }

  let mergedItems = incomingItems.map((item) => {
    if (!isUserMessageItem(item)) {
      return item;
    }
    const key = toComparableUserMessageKey(item);
    const bucket = localUserMessageMetadataBuckets.get(key);
    if (!bucket || bucket.length === 0) {
      return item;
    }
    if (hasUserSequenceDrift && bucket.length > 1) {
      return item;
    }
    const matchedLocalMetadata = bucket.shift();
    if (!matchedLocalMetadata) {
      return item;
    }
    if (bucket.length === 0) {
      localUserMessageMetadataBuckets.delete(key);
    } else {
      localUserMessageMetadataBuckets.set(key, bucket);
    }
    const incomingHasName = hasSelectedAgentName(item.selectedAgentName);
    const incomingHasIcon = hasSelectedAgentIcon(item.selectedAgentIcon);
    if (incomingHasName && incomingHasIcon) {
      return item;
    }
    return {
      ...item,
      selectedAgentName: incomingHasName
        ? item.selectedAgentName
        : matchedLocalMetadata.selectedAgentName,
      selectedAgentIcon: incomingHasIcon
        ? item.selectedAgentIcon
        : matchedLocalMetadata.selectedAgentIcon,
    };
  });

  if (isProcessing && localItems.length > 0) {
    const trailingOptimisticUsers: UserMessageItem[] = [];
    for (let index = localItems.length - 1; index >= 0; index -= 1) {
      const item = localItems[index];
      if (!item) {
        continue;
      }
      if (!isOptimisticUserMessage(item)) {
        break;
      }
      trailingOptimisticUsers.unshift(item);
    }
    if (trailingOptimisticUsers.length > 0) {
      const preservedOptimisticUsers = trailingOptimisticUsers.filter(
        (item) => !findMatchingRealUserMessage(mergedItems, item),
      );
      if (preservedOptimisticUsers.length > 0) {
        mergedItems = [...mergedItems, ...preservedOptimisticUsers];
      }
    }
  }

  if (isProcessing) {
    // Keep locally generated requestUserInput submitted records visible while
    // the thread is still processing and backend snapshot may lag.
    const incomingIds = new Set(mergedItems.map((item) => item.id));
    const preservedSubmittedItems = localItems.filter(
      (item) =>
        item.kind === "tool" &&
        item.toolType === "requestUserInputSubmitted" &&
        !incomingIds.has(item.id),
    );
    if (preservedSubmittedItems.length > 0) {
      mergedItems = [...mergedItems, ...preservedSubmittedItems];
    }
  }

  return mergedItems;
}

function getAssistantTextForRename(
  items: ConversationItem[],
  itemId?: string,
): string {
  if (itemId) {
    const match = items.find(
      (item) =>
        item.kind === "message" &&
        item.role === "assistant" &&
        item.id === itemId,
    );
    if (match && match.kind === "message") {
      return match.text;
    }
  }
  for (let index = items.length - 1; index >= 0; index -= 1) {
    const item = items[index];
    if (!item) {
      continue;
    }
    if (isAssistantMessageItem(item)) {
      return item.text;
    }
  }
  return "";
}

function maybeRenameThreadFromAgent({
  workspaceId,
  threadId,
  items,
  itemId,
  hasCustomName,
  threadsByWorkspace,
}: {
  workspaceId: string;
  threadId: string;
  items: ConversationItem[];
  itemId?: string;
  hasCustomName: boolean;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
}) {
  const threads = threadsByWorkspace[workspaceId] ?? [];
  if (!threads.length) {
    return threadsByWorkspace;
  }
  const hasUserMessage = items.some(
    (item) => item.kind === "message" && item.role === "user",
  );
  if (hasUserMessage) {
    return threadsByWorkspace;
  }
  if (hasCustomName) {
    return threadsByWorkspace;
  }
  const nextName = formatThreadName(getAssistantTextForRename(items, itemId));
  if (!nextName) {
    return threadsByWorkspace;
  }
  let didChange = false;
  const nextThreads = threads.map((thread) => {
    if (
      thread.id !== threadId ||
      thread.name === nextName ||
      !looksAutoGeneratedThreadName(thread.name)
    ) {
      return thread;
    }
    didChange = true;
    return { ...thread, name: nextName };
  });
  return didChange
    ? { ...threadsByWorkspace, [workspaceId]: nextThreads }
    : threadsByWorkspace;
}

function isFailedToolStatus(status: string) {
  return /(fail|error|cancel(?:led)?|abort|timeout|timed[_ -]?out)/.test(status);
}

function isCompletedToolStatus(status: string) {
  return /(complete|completed|success|done|finish(?:ed)?|succeed(?:ed)?)/.test(
    status,
  );
}

function isPendingToolStatus(status: string) {
  return /(pending|running|processing|started|in[_ -]?progress|inprogress|queued)/.test(
    status,
  );
}

type ThreadActivityStatus = {
  isProcessing: boolean;
  hasUnread: boolean;
  isReviewing: boolean;
  isContextCompacting?: boolean;
  processingStartedAt: number | null;
  lastDurationMs: number | null;
  heartbeatPulse?: number;
};

export type ThreadState = {
  activeThreadIdByWorkspace: Record<string, string | null>;
  itemsByThread: Record<string, ConversationItem[]>;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
  hiddenThreadIdsByWorkspace: Record<string, Record<string, true>>;
  threadParentById: Record<string, string>;
  threadStatusById: Record<string, ThreadActivityStatus>;
  threadListLoadingByWorkspace: Record<string, boolean>;
  threadListPagingByWorkspace: Record<string, boolean>;
  threadListCursorByWorkspace: Record<string, string | null>;
  activeTurnIdByThread: Record<string, string | null>;
  approvals: ApprovalRequest[];
  userInputRequests: RequestUserInputRequest[];
  tokenUsageByThread: Record<string, ThreadTokenUsage>;
  rateLimitsByWorkspace: Record<string, RateLimitSnapshot | null>;
  accountByWorkspace: Record<string, AccountSnapshot | null>;
  planByThread: Record<string, TurnPlan | null>;
  lastAgentMessageByThread: Record<string, { text: string; timestamp: number }>;
  // 流式消息分段：当 tool item 开始时增加，确保文本和工具交替显示
  agentSegmentByThread: Record<string, number>;
};

export type ThreadAction =
  | { type: "setActiveThreadId"; workspaceId: string; threadId: string | null }
  | {
      type: "ensureThread";
      workspaceId: string;
      threadId: string;
      engine?: "codex" | "claude" | "gemini" | "opencode";
    }
  | { type: "hideThread"; workspaceId: string; threadId: string }
  | { type: "removeThread"; workspaceId: string; threadId: string }
  | { type: "setThreadParent"; threadId: string; parentId: string }
  | {
      type: "markProcessing";
      threadId: string;
      isProcessing: boolean;
      timestamp: number;
    }
  | {
      type: "markContextCompacting";
      threadId: string;
      isCompacting: boolean;
    }
  | { type: "markHeartbeat"; threadId: string; pulse: number }
  | {
      type: "finalizePendingToolStatuses";
      threadId: string;
      status: "completed" | "failed";
    }
  | { type: "markReviewing"; threadId: string; isReviewing: boolean }
  | { type: "markUnread"; threadId: string; hasUnread: boolean }
  | { type: "addAssistantMessage"; threadId: string; text: string }
  | { type: "setThreadName"; workspaceId: string; threadId: string; name: string }
  | {
      type: "setThreadEngine";
      workspaceId: string;
      threadId: string;
      engine: "codex" | "claude" | "gemini" | "opencode";
    }
  | {
      type: "setThreadTimestamp";
      workspaceId: string;
      threadId: string;
      timestamp: number;
    }
  | {
      type: "appendAgentDelta";
      workspaceId: string;
      threadId: string;
      itemId: string;
      delta: string;
      hasCustomName: boolean;
    }
  | {
      type: "completeAgentMessage";
      workspaceId: string;
      threadId: string;
      itemId: string;
      text: string;
      hasCustomName: boolean;
      timestamp?: number;
    }
  | {
      type: "upsertItem";
      workspaceId: string;
      threadId: string;
      item: ConversationItem;
      hasCustomName?: boolean;
    }
  | { type: "evictThreadItems"; threadIds: string[] }
  | { type: "setThreadItems"; threadId: string; items: ConversationItem[] }
  | {
      type: "appendReasoningSummary";
      threadId: string;
      itemId: string;
      delta: string;
    }
  | {
      type: "appendReasoningSummaryBoundary";
      threadId: string;
      itemId: string;
    }
  | {
      type: "appendContextCompacted";
      threadId: string;
      turnId: string;
    }
  | { type: "appendReasoningContent"; threadId: string; itemId: string; delta: string }
  | { type: "dropReasoningItems"; threadId: string }
  | { type: "appendToolOutput"; threadId: string; itemId: string; delta: string }
  | { type: "setThreads"; workspaceId: string; threads: ThreadSummary[] }
  | {
      type: "setThreadListLoading";
      workspaceId: string;
      isLoading: boolean;
    }
  | {
      type: "setThreadListPaging";
      workspaceId: string;
      isLoading: boolean;
    }
  | {
      type: "setThreadListCursor";
      workspaceId: string;
      cursor: string | null;
    }
  | { type: "addApproval"; approval: ApprovalRequest }
  | { type: "removeApproval"; requestId: number | string; workspaceId: string }
  | { type: "addUserInputRequest"; request: RequestUserInputRequest }
  | {
      type: "removeUserInputRequest";
      requestId: number | string;
      workspaceId: string;
    }
  | {
      type: "clearUserInputRequestsForThread";
      workspaceId: string;
      threadId: string;
    }
  | { type: "setThreadTokenUsage"; threadId: string; tokenUsage: ThreadTokenUsage }
  | {
      type: "setRateLimits";
      workspaceId: string;
      rateLimits: RateLimitSnapshot | null;
    }
  | {
      type: "setAccountInfo";
      workspaceId: string;
      account: AccountSnapshot | null;
    }
  | { type: "setActiveTurnId"; threadId: string; turnId: string | null }
  | { type: "setThreadPlan"; threadId: string; plan: TurnPlan | null }
  | {
      type: "settleThreadPlanInProgress";
      threadId: string;
      targetStatus: "pending" | "completed";
    }
  | { type: "clearThreadPlan"; threadId: string }
  | { type: "incrementAgentSegment"; threadId: string }
  | { type: "resetAgentSegment"; threadId: string }
  | { type: "markLatestAssistantMessageFinal"; threadId: string }
  | {
      type: "setLastAgentMessage";
      threadId: string;
      text: string;
      timestamp: number;
    }
  | {
      type: "renameThreadId";
      workspaceId: string;
      oldThreadId: string;
      newThreadId: string;
    };

const emptyItems: Record<string, ConversationItem[]> = {};

export const initialState: ThreadState = {
  activeThreadIdByWorkspace: {},
  itemsByThread: emptyItems,
  threadsByWorkspace: {},
  hiddenThreadIdsByWorkspace: {},
  threadParentById: {},
  threadStatusById: {},
  threadListLoadingByWorkspace: {},
  threadListPagingByWorkspace: {},
  threadListCursorByWorkspace: {},
  activeTurnIdByThread: {},
  approvals: [],
  userInputRequests: [],
  tokenUsageByThread: {},
  rateLimitsByWorkspace: {},
  accountByWorkspace: {},
  planByThread: {},
  lastAgentMessageByThread: {},
  agentSegmentByThread: {},
};


function findAssistantMessageIndexById(
  list: ConversationItem[],
  candidateId: string,
) {
  if (!candidateId) {
    return -1;
  }
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const item = list[index];
    if (!item) {
      continue;
    }
    if (
      isAssistantMessageItem(item) &&
      item.id === candidateId
    ) {
      return index;
    }
  }
  return -1;
}

function findAssistantMessageIndexByPrefix(
  list: ConversationItem[],
  idPrefix: string,
) {
  if (!idPrefix) {
    return -1;
  }
  const segmentPrefix = `${idPrefix}-seg-`;
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const item = list[index];
    if (!item) {
      continue;
    }
    if (
      isAssistantMessageItem(item) &&
      item.id.startsWith(segmentPrefix)
    ) {
      return index;
    }
  }
  return -1;
}

function resolveLiveAssistantMessageId(
  state: ThreadState,
  threadId: string,
  itemId: string,
) {
  const segment = state.agentSegmentByThread[threadId] ?? 0;
  const normalizedItemId = itemId.trim();
  // Prefer backend item id for local CLI threads to avoid cross-turn overwrite races.
  // Realtime events may arrive after activeTurnId has advanced to the next turn.
  if (normalizedItemId.length > 0) {
    return segment > 0 ? `${normalizedItemId}-seg-${segment}` : normalizedItemId;
  }
  const activeTurnId = state.activeTurnIdByThread[threadId] ?? null;
  if (isLocalCliReasoningThread(threadId) && activeTurnId) {
    return segment > 0
      ? `assistant-live:${activeTurnId}:seg-${segment}`
      : `assistant-live:${activeTurnId}`;
  }
  return segment > 0 ? `${itemId}-seg-${segment}` : itemId;
}

function resolveLiveReasoningItemId(
  state: ThreadState,
  threadId: string,
  itemId: string,
) {
  if (!isLocalCliReasoningThread(threadId)) {
    return itemId;
  }
  const segment = state.agentSegmentByThread[threadId] ?? 0;
  return segment > 0 ? `${itemId}-seg-${segment}` : itemId;
}


function dropLatestLocalReviewStart(list: ConversationItem[]) {
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const item = list[index];
    if (!item) {
      continue;
    }
    if (
      item.kind === "review" &&
      item.state === "started" &&
      item.id.startsWith("review-start-")
    ) {
      return [...list.slice(0, index), ...list.slice(index + 1)];
    }
  }
  return list;
}

function findMatchingReview(
  list: ConversationItem[],
  target: Extract<ConversationItem, { kind: "review" }>,
) {
  const normalizedText = target.text.trim();
  return list.find(
    (item) =>
      item.kind === "review" &&
      item.state === target.state &&
      item.text.trim() === normalizedText,
  );
}

function ensureUniqueReviewId(list: ConversationItem[], item: ConversationItem) {
  if (item.kind !== "review") {
    return item;
  }
  if (!list.some((entry) => entry.id === item.id)) {
    return item;
  }
  const existingIds = new Set(list.map((entry) => entry.id));
  let suffix = 1;
  let candidate = `${item.id}-${suffix}`;
  while (existingIds.has(candidate)) {
    suffix += 1;
    candidate = `${item.id}-${suffix}`;
  }
  return { ...item, id: candidate };
}

function isDuplicateReviewById(
  list: ConversationItem[],
  target: Extract<ConversationItem, { kind: "review" }>,
) {
  const normalizedText = target.text.trim();
  return list.some(
    (item) =>
      item.kind === "review" &&
      item.id === target.id &&
      item.state === target.state &&
      item.text.trim() === normalizedText,
  );
}

function clearAssistantFinalMetadata(
  item: AssistantMessageItem,
): AssistantMessageItem {
  const {
    finalCompletedAt: _finalCompletedAt,
    finalDurationMs: _finalDurationMs,
    ...rest
  } = item;
  return rest as AssistantMessageItem;
}

function shouldPreserveAssistantFinalMetadata(
  item: AssistantMessageItem,
  isThreadProcessing: boolean,
) {
  return item.isFinal === true && !isThreadProcessing;
}

export function threadReducer(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "setActiveThreadId":
      return {
        ...state,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: action.threadId,
        },
        threadStatusById: action.threadId
          ? {
              ...state.threadStatusById,
              [action.threadId]: {
                isProcessing:
                  state.threadStatusById[action.threadId]?.isProcessing ?? false,
                hasUnread: false,
                isReviewing:
                  state.threadStatusById[action.threadId]?.isReviewing ?? false,
                isContextCompacting:
                  state.threadStatusById[action.threadId]?.isContextCompacting ??
                  false,
                processingStartedAt:
                  state.threadStatusById[action.threadId]?.processingStartedAt ??
                  null,
                lastDurationMs:
                  state.threadStatusById[action.threadId]?.lastDurationMs ?? null,
                heartbeatPulse:
                  state.threadStatusById[action.threadId]?.heartbeatPulse ?? 0,
              },
            }
          : state.threadStatusById,
      };
    case "ensureThread": {
      const hidden =
        state.hiddenThreadIdsByWorkspace[action.workspaceId]?.[action.threadId] ??
        false;
      if (hidden) {
        return state;
      }
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      let existingIndex = list.findIndex((thread) => thread.id === action.threadId);
      if (existingIndex < 0 && !action.threadId.includes(":")) {
        const aliasIndexes = list
          .map((thread, index) => ({ thread, index }))
          .filter(({ thread }) => thread.id.endsWith(`:${action.threadId}`))
          .map(({ index }) => index);
        if (aliasIndexes.length === 1) {
          existingIndex = aliasIndexes[0] ?? -1;
        }
      }
      if (existingIndex >= 0) {
        const existing = list[existingIndex];
        if (!existing) {
          return state;
        }
        // BUG FIX: Only update engineSource if action.engine is explicitly provided
        // AND the existing engineSource is not already set.
        // This prevents inferred engines (from inferEngineFromThreadId) from
        // overwriting explicitly set engines.
        if (!action.engine || existing.engineSource) {
          return state;
        }
        const updated = { ...existing, engineSource: action.engine };
        const nextList = [...list];
        nextList[existingIndex] = updated;
        return {
          ...state,
          threadsByWorkspace: {
            ...state.threadsByWorkspace,
            [action.workspaceId]: nextList,
          },
        };
      }

      // CRITICAL FIX: Handle race condition between renameThreadId and subsequent events.
      // If threadId is engine:{sessionId} but not found, check for pending thread to rename.
      const pendingPrefix = action.threadId.startsWith("claude:")
        ? "claude-pending-"
        : action.threadId.startsWith("gemini:")
          ? "gemini-pending-"
        : action.threadId.startsWith("opencode:")
          ? "opencode-pending-"
          : null;
      if (pendingPrefix) {
        const pendingIndexes: number[] = [];
        list.forEach((thread, index) => {
          if (thread.id.startsWith(pendingPrefix)) {
            pendingIndexes.push(index);
          }
        });

        const hasPendingThreadAnchor = (threadId: string) => {
          const hasActiveTurn = (state.activeTurnIdByThread[threadId] ?? null) !== null;
          if (hasActiveTurn) {
            return true;
          }
          const isProcessing = Boolean(state.threadStatusById[threadId]?.isProcessing);
          const hasObservedItems = (state.itemsByThread[threadId]?.length ?? 0) > 0;
          return isProcessing && hasObservedItems;
        };
        const activePendingId = state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
        const resolveActivePendingIndex = (): number | null => {
          if (!activePendingId || !activePendingId.startsWith(pendingPrefix)) {
            return null;
          }
          const activeIndex = pendingIndexes.find(
            (index) => list[index]?.id === activePendingId,
          );
          if (activeIndex === undefined) {
            return null;
          }
          const threadId = list[activeIndex]?.id ?? "";
          if (!threadId || !hasPendingThreadAnchor(threadId)) {
            return null;
          }
          return activeIndex;
        };

        // Boundary first: when multiple pending threads exist for the same engine,
        // never auto-rename here. The incoming finalized session event may belong
        // to any pending stream, and guessing can cross-bind sessions.
        //
        // We rely on explicit thread/session mapping (thread/sessionIdUpdated) to
        // reconcile those cases safely.
        let pendingIndex: number | null = null;
        if (pendingIndexes.length === 1) {
          const singlePendingIndex = pendingIndexes[0];
          const singlePendingId =
            singlePendingIndex !== undefined ? (list[singlePendingIndex]?.id ?? "") : "";
          if (singlePendingId && hasPendingThreadAnchor(singlePendingId)) {
            pendingIndex = singlePendingIndex ?? null;
          }
        } else if (pendingIndexes.length === 0) {
          pendingIndex = resolveActivePendingIndex();
        }

        if (pendingIndex !== null) {
          // Found a pending thread - perform inline rename to avoid race condition
          const pendingThread = list[pendingIndex];
          if (!pendingThread) {
            return state;
          }
          const oldThreadId = pendingThread.id;
          const newThreadId = action.threadId;

          // Rename thread inline (similar to renameThreadId action)
          const updatedThread = { ...pendingThread, id: newThreadId };
          const nextList = [...list];
          nextList[pendingIndex] = updatedThread;

          // Update all related state maps
          const newItemsByThread = { ...state.itemsByThread };
          if (newItemsByThread[oldThreadId]) {
            newItemsByThread[newThreadId] = newItemsByThread[oldThreadId];
            delete newItemsByThread[oldThreadId];
          }

          const newThreadStatusById = { ...state.threadStatusById };
          if (newThreadStatusById[oldThreadId]) {
            newThreadStatusById[newThreadId] = newThreadStatusById[oldThreadId];
            delete newThreadStatusById[oldThreadId];
          }

          const newActiveTurnIdByThread = { ...state.activeTurnIdByThread };
          if (newActiveTurnIdByThread[oldThreadId] !== undefined) {
            newActiveTurnIdByThread[newThreadId] = newActiveTurnIdByThread[oldThreadId];
            delete newActiveTurnIdByThread[oldThreadId];
          }

          const newActiveThreadIdByWorkspace = { ...state.activeThreadIdByWorkspace };
          if (newActiveThreadIdByWorkspace[action.workspaceId] === oldThreadId) {
            newActiveThreadIdByWorkspace[action.workspaceId] = newThreadId;
          }

          const newTokenUsageByThread = { ...state.tokenUsageByThread };
          if (newTokenUsageByThread[oldThreadId]) {
            newTokenUsageByThread[newThreadId] = newTokenUsageByThread[oldThreadId];
            delete newTokenUsageByThread[oldThreadId];
          }

          const newPlanByThread = { ...state.planByThread };
          if (newPlanByThread[oldThreadId] !== undefined) {
            newPlanByThread[newThreadId] = newPlanByThread[oldThreadId];
            delete newPlanByThread[oldThreadId];
          }

          const newLastAgentMessageByThread = { ...state.lastAgentMessageByThread };
          if (newLastAgentMessageByThread[oldThreadId]) {
            newLastAgentMessageByThread[newThreadId] = newLastAgentMessageByThread[oldThreadId];
            delete newLastAgentMessageByThread[oldThreadId];
          }

          const newAgentSegmentByThread = { ...state.agentSegmentByThread };
          if (newAgentSegmentByThread[oldThreadId] !== undefined) {
            newAgentSegmentByThread[newThreadId] = newAgentSegmentByThread[oldThreadId];
            delete newAgentSegmentByThread[oldThreadId];
          }

          const newThreadParentById = { ...state.threadParentById };
          if (newThreadParentById[oldThreadId]) {
            newThreadParentById[newThreadId] = newThreadParentById[oldThreadId];
            delete newThreadParentById[oldThreadId];
          }
          for (const [threadId, parentId] of Object.entries(newThreadParentById)) {
            if (parentId === oldThreadId) {
              newThreadParentById[threadId] = newThreadId;
            }
          }

          return {
            ...state,
            threadsByWorkspace: {
              ...state.threadsByWorkspace,
              [action.workspaceId]: nextList,
            },
            itemsByThread: newItemsByThread,
            threadStatusById: newThreadStatusById,
            activeTurnIdByThread: newActiveTurnIdByThread,
            activeThreadIdByWorkspace: newActiveThreadIdByWorkspace,
            tokenUsageByThread: newTokenUsageByThread,
            planByThread: newPlanByThread,
            lastAgentMessageByThread: newLastAgentMessageByThread,
            agentSegmentByThread: newAgentSegmentByThread,
            threadParentById: newThreadParentById,
          };
        }
      }

      // No existing thread and no pending thread to rename - create new thread
      const thread: ThreadSummary = {
        id: action.threadId,
        name: `Agent ${list.length + 1}`,
        updatedAt: 0,
        engineSource: action.engine,
      };
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: [thread, ...list],
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: false,
            hasUnread: false,
            isReviewing: false,
            isContextCompacting: false,
            processingStartedAt: null,
            lastDurationMs: null,
            heartbeatPulse: 0,
          },
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]:
            state.activeThreadIdByWorkspace[action.workspaceId] ?? action.threadId,
        },
      };
    }
    case "hideThread": {
      const hiddenForWorkspace =
        state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      if (hiddenForWorkspace[action.threadId]) {
        return state;
      }

      const nextHiddenForWorkspace = {
        ...hiddenForWorkspace,
        [action.threadId]: true as const,
      };

      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;

      return {
        ...state,
        hiddenThreadIdsByWorkspace: {
          ...state.hiddenThreadIdsByWorkspace,
          [action.workspaceId]: nextHiddenForWorkspace,
        },
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "removeThread": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? filtered[0]?.id ?? null
          : state.activeThreadIdByWorkspace[action.workspaceId] ?? null;
      const { [action.threadId]: _items, ...restItems } = state.itemsByThread;
      const { [action.threadId]: _status, ...restStatus } = state.threadStatusById;
      const { [action.threadId]: _turns, ...restTurns } = state.activeTurnIdByThread;
      const { [action.threadId]: _plans, ...restPlans } = state.planByThread;
      const { [action.threadId]: _parents, ...restParents } = state.threadParentById;
      const { [action.threadId]: _tokenUsage, ...restTokenUsage } = state.tokenUsageByThread;
      const { [action.threadId]: _lastAgent, ...restLastAgent } = state.lastAgentMessageByThread;
      const { [action.threadId]: _segments, ...restSegments } = state.agentSegmentByThread;
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        itemsByThread: restItems,
        threadStatusById: restStatus,
        activeTurnIdByThread: restTurns,
        planByThread: restPlans,
        threadParentById: restParents,
        tokenUsageByThread: restTokenUsage,
        lastAgentMessageByThread: restLastAgent,
        agentSegmentByThread: restSegments,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "evictThreadItems": {
      if (!action.threadIds.length) {
        return state;
      }
      const nextItemsByThread = { ...state.itemsByThread };
      let didChange = false;
      action.threadIds.forEach((threadId) => {
        if (!(threadId in nextItemsByThread)) {
          return;
        }
        delete nextItemsByThread[threadId];
        didChange = true;
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        itemsByThread: nextItemsByThread,
      };
    }
    case "setThreadParent": {
      if (!action.parentId || action.parentId === action.threadId) {
        return state;
      }
      if (state.threadParentById[action.threadId] === action.parentId) {
        return state;
      }
      return {
        ...state,
        threadParentById: {
          ...state.threadParentById,
          [action.threadId]: action.parentId,
        },
      };
    }
    case "markProcessing": {
      const previous = state.threadStatusById[action.threadId];
      const wasProcessing = previous?.isProcessing ?? false;
      const startedAt = previous?.processingStartedAt ?? null;
      const lastDurationMs = previous?.lastDurationMs ?? null;
      const heartbeatPulse = previous?.heartbeatPulse ?? 0;
      if (action.isProcessing) {
        if (REDUCER_NOOP_GUARD_ENABLED && wasProcessing) {
          return state;
        }
        return {
          ...state,
          threadStatusById: {
            ...state.threadStatusById,
            [action.threadId]: {
              isProcessing: true,
              hasUnread: previous?.hasUnread ?? false,
              isReviewing: previous?.isReviewing ?? false,
              isContextCompacting: previous?.isContextCompacting ?? false,
              processingStartedAt:
                wasProcessing && startedAt ? startedAt : action.timestamp,
              lastDurationMs,
              heartbeatPulse: wasProcessing ? heartbeatPulse : 0,
            },
          },
        };
      }
      if (
        REDUCER_NOOP_GUARD_ENABLED &&
        (!previous ||
          (!wasProcessing &&
            previous.processingStartedAt == null &&
            (previous.heartbeatPulse ?? 0) === 0))
      ) {
        return state;
      }
      const nextDuration =
        wasProcessing && startedAt
          ? Math.max(0, action.timestamp - startedAt)
          : lastDurationMs ?? null;
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: false,
            hasUnread: previous?.hasUnread ?? false,
            isReviewing: previous?.isReviewing ?? false,
            isContextCompacting: previous?.isContextCompacting ?? false,
            processingStartedAt: null,
            lastDurationMs: nextDuration,
            heartbeatPulse: 0,
          },
        },
      };
    }
    case "markContextCompacting": {
      const previous = state.threadStatusById[action.threadId];
      const currentIsCompacting = previous?.isContextCompacting ?? false;
      if (currentIsCompacting === action.isCompacting) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: previous?.isProcessing ?? false,
            hasUnread: previous?.hasUnread ?? false,
            isReviewing: previous?.isReviewing ?? false,
            isContextCompacting: action.isCompacting,
            processingStartedAt: previous?.processingStartedAt ?? null,
            lastDurationMs: previous?.lastDurationMs ?? null,
            heartbeatPulse: previous?.heartbeatPulse ?? 0,
          },
        },
      };
    }
    case "markHeartbeat": {
      const previous = state.threadStatusById[action.threadId];
      if (!previous?.isProcessing) {
        return state;
      }
      if (action.pulse <= 0 || action.pulse <= (previous.heartbeatPulse ?? 0)) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            ...previous,
            heartbeatPulse: action.pulse,
          },
        },
      };
    }
    case "finalizePendingToolStatuses": {
      const list = state.itemsByThread[action.threadId] ?? [];
      let didChange = false;

      const nextItems = list.map((item) => {
        if (item.kind !== "tool") {
          return item;
        }

        const normalizedStatus = (item.status ?? "").toLowerCase();
        if (
          isFailedToolStatus(normalizedStatus) ||
          isCompletedToolStatus(normalizedStatus)
        ) {
          return item;
        }

        if (!normalizedStatus || isPendingToolStatus(normalizedStatus)) {
          didChange = true;
          return {
            ...item,
            status: action.status,
          };
        }

        return item;
      });

      if (!didChange) {
        return state;
      }

      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(nextItems),
        },
      };
    }
    case "setActiveTurnId":
      return {
        ...state,
        activeTurnIdByThread: {
          ...state.activeTurnIdByThread,
          [action.threadId]: action.turnId,
        },
      };
    case "markReviewing":
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing:
              state.threadStatusById[action.threadId]?.isProcessing ?? false,
            hasUnread: state.threadStatusById[action.threadId]?.hasUnread ?? false,
            isReviewing: action.isReviewing,
            isContextCompacting:
              state.threadStatusById[action.threadId]?.isContextCompacting ??
              false,
            processingStartedAt:
              state.threadStatusById[action.threadId]?.processingStartedAt ?? null,
            lastDurationMs:
              state.threadStatusById[action.threadId]?.lastDurationMs ?? null,
            heartbeatPulse:
              state.threadStatusById[action.threadId]?.heartbeatPulse ?? 0,
          },
        },
      };
    case "markUnread":
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing:
              state.threadStatusById[action.threadId]?.isProcessing ?? false,
            hasUnread: action.hasUnread,
            isReviewing:
              state.threadStatusById[action.threadId]?.isReviewing ?? false,
            isContextCompacting:
              state.threadStatusById[action.threadId]?.isContextCompacting ??
              false,
            processingStartedAt:
              state.threadStatusById[action.threadId]?.processingStartedAt ?? null,
            lastDurationMs:
              state.threadStatusById[action.threadId]?.lastDurationMs ?? null,
            heartbeatPulse:
              state.threadStatusById[action.threadId]?.heartbeatPulse ?? 0,
          },
        },
      };
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, message]),
        },
      };
    }
    case "setThreadName": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId ? { ...thread, name: action.name } : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadEngine": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId
          ? { ...thread, engineSource: action.engine }
          : thread,
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadTimestamp": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (!list.length) {
        return state;
      }
      let didChange = false;
      const next = list.map((thread) => {
        if (thread.id !== action.threadId) {
          return thread;
        }
        const current = thread.updatedAt ?? 0;
        if (current >= action.timestamp) {
          return thread;
        }
        didChange = true;
        return { ...thread, updatedAt: action.timestamp };
      });
      if (!didChange) {
        return state;
      }
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "appendAgentDelta": {
      const segmentedItemId = resolveLiveAssistantMessageId(
        state,
        action.threadId,
        action.itemId,
      );

      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      let index = findAssistantMessageIndexById(list, segmentedItemId);
      let shouldCanonicalizeLegacyId = false;
      if (index < 0 && !isLegacyTextDeltaItemId(action.threadId, segmentedItemId)) {
        const legacySegmentedItemId = resolveLiveAssistantMessageId(
          state,
          action.threadId,
          buildLegacyTextDeltaItemId(action.threadId),
        );
        index = findAssistantMessageIndexById(list, legacySegmentedItemId);
        if (index < 0) {
          index = findAssistantMessageIndexByLegacyTextDelta(list, action.threadId);
        }
        shouldCanonicalizeLegacyId = index >= 0;
      }
      if (index >= 0) {
        const existing = list[index];
        if (!existing || !isAssistantMessageItem(existing)) {
          return state;
        }
        const isThreadProcessing = Boolean(state.threadStatusById[action.threadId]?.isProcessing);
        const keepFinalMetadata = shouldPreserveAssistantFinalMetadata(
          existing,
          isThreadProcessing,
        );
        const nextId = shouldCanonicalizeLegacyId ? segmentedItemId : existing.id;
        const nextText = mergeAgentMessageText(existing.text, action.delta);
        if (
          INCREMENTAL_DERIVATION_ENABLED &&
          nextId === existing.id &&
          nextText === existing.text
        ) {
          return state;
        }
        const nextBase = keepFinalMetadata
          ? existing
          : clearAssistantFinalMetadata(existing);
        list[index] = {
          ...nextBase,
          id: nextId,
          text: nextText,
          isFinal: keepFinalMetadata ? true : false,
        };
      } else {
        list.push({
          id: segmentedItemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
          isFinal: false,
        });
      }
      const updatedItems = prepareThreadItems(list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: segmentedItemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const segmentedItemId = resolveLiveAssistantMessageId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      let index = findAssistantMessageIndexById(list, segmentedItemId);
      if (index < 0) {
        index = findAssistantMessageIndexById(list, action.itemId);
      }
      if (index < 0) {
        index = findAssistantMessageIndexByPrefix(list, action.itemId);
      }
      let shouldCanonicalizeLegacyId = false;
      if (index < 0 && !isLegacyTextDeltaItemId(action.threadId, segmentedItemId)) {
        const legacySegmentedItemId = resolveLiveAssistantMessageId(
          state,
          action.threadId,
          buildLegacyTextDeltaItemId(action.threadId),
        );
        index = findAssistantMessageIndexById(list, legacySegmentedItemId);
        if (index < 0) {
          index = findAssistantMessageIndexByLegacyTextDelta(list, action.threadId);
        }
        shouldCanonicalizeLegacyId = index >= 0;
      }
      const targetItemId =
        index >= 0
          ? shouldCanonicalizeLegacyId
            ? segmentedItemId
            : (list[index]?.id ?? segmentedItemId)
          : segmentedItemId;
      const completedAt = action.timestamp ?? Date.now();
      const status = state.threadStatusById[action.threadId];
      const statusDuration =
        typeof status?.lastDurationMs === "number"
          ? Math.max(0, status.lastDurationMs)
          : null;
      const derivedDuration =
        statusDuration !== null
          ? statusDuration
          : status?.processingStartedAt
            ? Math.max(0, completedAt - status.processingStartedAt)
            : null;
      const existingItem = index >= 0 ? list[index] : undefined;
      if (isAssistantMessageItem(existingItem)) {
        const isThreadProcessing = Boolean(state.threadStatusById[action.threadId]?.isProcessing);
        const keepFinalMetadata = shouldPreserveAssistantFinalMetadata(
          existingItem,
          isThreadProcessing,
        );
        const nextBase = keepFinalMetadata
          ? existingItem
          : clearAssistantFinalMetadata(existingItem);
        list[index] = {
          ...nextBase,
          id: targetItemId,
          text: mergeCompletedAgentText(existingItem.text, action.text),
          isFinal: true,
          finalCompletedAt: nextBase.finalCompletedAt ?? completedAt,
          ...(typeof nextBase.finalDurationMs === "number"
            ? { finalDurationMs: nextBase.finalDurationMs }
            : derivedDuration !== null
              ? { finalDurationMs: derivedDuration }
              : {}),
        };
      } else {
        list.push({
          id: targetItemId,
          kind: "message",
          role: "assistant",
          text: action.text,
          isFinal: true,
          finalCompletedAt: completedAt,
          ...(derivedDuration !== null ? { finalDurationMs: derivedDuration } : {}),
        });
      }
      const updatedItems = prepareThreadItems(list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: targetItemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const isUserMessage = isUserMessageItem(item);
      const isOptimisticUser =
        isUserMessage && item.id.startsWith(OPTIMISTIC_USER_ITEM_PREFIX);
      if (isUserMessage && !isOptimisticUser) {
        list = dropMatchingOptimisticUserMessage(list, item);
      }
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      let nextItem = ensureUniqueReviewId(list, item);
      if (nextItem.kind === "reasoning") {
        const segmentedReasoningId = resolveLiveReasoningItemId(
          state,
          action.threadId,
          nextItem.id,
        );
        if (segmentedReasoningId !== nextItem.id) {
          nextItem = { ...nextItem, id: segmentedReasoningId };
        }
        const existingReasoning = list.find(
          (entry): entry is Extract<ConversationItem, { kind: "reasoning" }> =>
            entry.id === nextItem.id && entry.kind === "reasoning",
        );
        if (existingReasoning) {
          const existingSummary = normalizeReasoningReadableText(existingReasoning.summary);
          const incomingSummary = normalizeReasoningReadableText(nextItem.summary);
          const existingContent = normalizeReasoningReadableText(existingReasoning.content);
          const incomingContent = normalizeReasoningReadableText(nextItem.content);
          nextItem = {
            ...nextItem,
            summary: mergeReasoningSnapshotTextForThread(
              action.threadId,
              existingSummary,
              incomingSummary,
            ),
            content: mergeReasoningSnapshotTextForThread(
              action.threadId,
              existingContent,
              incomingContent,
            ),
          };
        } else {
          const normalizedIncoming = {
            ...nextItem,
            summary: normalizeReasoningReadableText(nextItem.summary),
            content: normalizeReasoningReadableText(nextItem.content),
          };
          const duplicateIndex = findDuplicateReasoningSnapshotIndex(
            list,
            normalizedIncoming,
          );
          if (
            duplicateIndex >= 0 &&
            list[duplicateIndex]?.kind === "reasoning"
          ) {
            const duplicate = list[duplicateIndex] as Extract<
              ConversationItem,
              { kind: "reasoning" }
            >;
            nextItem = {
              ...normalizedIncoming,
              id: duplicate.id,
              summary: mergeReasoningSnapshotTextForThread(
                action.threadId,
                duplicate.summary,
                normalizedIncoming.summary,
              ),
              content: mergeReasoningSnapshotTextForThread(
                action.threadId,
                duplicate.content,
                normalizedIncoming.content,
              ),
            };
          } else {
            nextItem = normalizedIncoming;
          }
        }
      }
      const updatedItems = prepareThreadItems(upsertItem(list, nextItem));
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName = shouldRename ? textValue : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads = updatedThreads.length
          ? [
              ...updatedThreads.filter((thread) => thread.id === action.threadId),
              ...updatedThreads.filter((thread) => thread.id !== action.threadId),
            ]
          : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "setThreadItems": {
      const localItems = state.itemsByThread[action.threadId] ?? [];
      const mergedItems = mergeThreadItemsPreservingOptimisticUsers(
        localItems,
        action.items,
        Boolean(state.threadStatusById[action.threadId]?.isProcessing),
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(mergedItems),
        },
      };
    }
    case "markLatestAssistantMessageFinal": {
      const list = state.itemsByThread[action.threadId] ?? [];
      if (list.length === 0) {
        return state;
      }
      let latestAssistantIndex = -1;
      for (let index = list.length - 1; index >= 0; index -= 1) {
        const item = list[index];
        if (isAssistantMessageItem(item)) {
          latestAssistantIndex = index;
          break;
        }
      }
      if (latestAssistantIndex < 0) {
        return state;
      }
      const latestAssistant = list[latestAssistantIndex];
      if (!isAssistantMessageItem(latestAssistant)) {
        return state;
      }
      const completedAt =
        latestAssistant.finalCompletedAt ??
        Date.now();
      const status = state.threadStatusById[action.threadId];
      const statusDuration =
        typeof status?.lastDurationMs === "number"
          ? Math.max(0, status.lastDurationMs)
          : null;
      const derivedDuration =
        statusDuration !== null
          ? statusDuration
          : status?.processingStartedAt
            ? Math.max(0, completedAt - status.processingStartedAt)
            : null;
      const durationMs =
        typeof latestAssistant.finalDurationMs === "number"
          ? Math.max(0, latestAssistant.finalDurationMs)
          : derivedDuration;
      const shouldUpdate =
        latestAssistant.isFinal !== true ||
        latestAssistant.finalCompletedAt !== completedAt ||
        latestAssistant.finalDurationMs !== durationMs;
      if (!shouldUpdate) {
        return state;
      }
      const next = [...list];
      next[latestAssistantIndex] = {
        ...latestAssistant,
        isFinal: true,
        finalCompletedAt: completedAt,
        ...(durationMs !== null ? { finalDurationMs: durationMs } : {}),
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: next,
        },
      };
    }
    case "setLastAgentMessage":
      if (
        state.lastAgentMessageByThread[action.threadId] &&
        state.lastAgentMessageByThread[action.threadId]!.timestamp >= action.timestamp
      ) {
        return state;
      }
      return {
        ...state,
        lastAgentMessageByThread: {
          ...state.lastAgentMessageByThread,
          [action.threadId]: { text: action.text, timestamp: action.timestamp },
        },
      };
    case "renameThreadId": {
      const { workspaceId, oldThreadId, newThreadId } = action;
      if (oldThreadId === newThreadId) {
        return state;
      }

      // Update activeThreadIdByWorkspace
      const newActiveThreadIdByWorkspace = { ...state.activeThreadIdByWorkspace };
      if (newActiveThreadIdByWorkspace[workspaceId] === oldThreadId) {
        newActiveThreadIdByWorkspace[workspaceId] = newThreadId;
      }

      // Update itemsByThread
      const newItemsByThread = { ...state.itemsByThread };
      if (newItemsByThread[oldThreadId]) {
        const oldItems = newItemsByThread[oldThreadId] ?? [];
        const existingItems = newItemsByThread[newThreadId] ?? [];
        const oldHasUserMessage = oldItems.some(
          (item) => item.kind === "message" && item.role === "user",
        );
        const existingHasUserMessage = existingItems.some(
          (item) => item.kind === "message" && item.role === "user",
        );
        // If existing thread already has user history, append pending items to the tail
        // so the latest user prompt is not truncated out by MAX_ITEMS_PER_THREAD.
        // If existing thread only has assistant deltas (rename race), keep user-first order.
        const mergedItems =
          oldHasUserMessage && !existingHasUserMessage
            ? [...oldItems, ...existingItems]
            : [...existingItems, ...oldItems];
        newItemsByThread[newThreadId] = prepareThreadItems([
          ...mergedItems,
        ]);
        delete newItemsByThread[oldThreadId];
      }

      // Update threadsByWorkspace
      const newThreadsByWorkspace = { ...state.threadsByWorkspace };
      const workspaceThreads = newThreadsByWorkspace[workspaceId];
      if (workspaceThreads) {
        const renamedThreads = workspaceThreads.map((thread) =>
          thread.id === oldThreadId ? { ...thread, id: newThreadId } : thread,
        );
        const dedupedById = new Map<string, ThreadSummary>();
        for (const thread of renamedThreads) {
          const current = dedupedById.get(thread.id);
          if (!current) {
            dedupedById.set(thread.id, thread);
            continue;
          }
          dedupedById.set(thread.id, {
            ...current,
            ...thread,
            updatedAt: Math.max(current.updatedAt, thread.updatedAt),
          });
        }
        newThreadsByWorkspace[workspaceId] = Array.from(dedupedById.values());
      }

      // Update threadStatusById
      const newThreadStatusById = { ...state.threadStatusById };
      if (newThreadStatusById[oldThreadId]) {
        const oldStatus = newThreadStatusById[oldThreadId];
        const existingStatus = newThreadStatusById[newThreadId];
        newThreadStatusById[newThreadId] = existingStatus
          ? {
              isProcessing: oldStatus.isProcessing || existingStatus.isProcessing,
              hasUnread: oldStatus.hasUnread || existingStatus.hasUnread,
              isReviewing: oldStatus.isReviewing || existingStatus.isReviewing,
              isContextCompacting:
                (oldStatus.isContextCompacting ?? false)
                || (existingStatus.isContextCompacting ?? false),
              processingStartedAt:
                oldStatus.processingStartedAt ?? existingStatus.processingStartedAt,
              lastDurationMs:
                oldStatus.lastDurationMs ?? existingStatus.lastDurationMs,
              heartbeatPulse:
                oldStatus.heartbeatPulse ?? existingStatus.heartbeatPulse ?? 0,
            }
          : oldStatus;
        delete newThreadStatusById[oldThreadId];
      }

      // Update activeTurnIdByThread
      const newActiveTurnIdByThread = { ...state.activeTurnIdByThread };
      if (newActiveTurnIdByThread[oldThreadId] !== undefined) {
        newActiveTurnIdByThread[newThreadId] =
          newActiveTurnIdByThread[oldThreadId] ??
          newActiveTurnIdByThread[newThreadId] ??
          null;
        delete newActiveTurnIdByThread[oldThreadId];
      }

      // Update tokenUsageByThread
      const newTokenUsageByThread = { ...state.tokenUsageByThread };
      if (newTokenUsageByThread[oldThreadId]) {
        newTokenUsageByThread[newThreadId] =
          newTokenUsageByThread[newThreadId] ?? newTokenUsageByThread[oldThreadId];
        delete newTokenUsageByThread[oldThreadId];
      }

      // Update planByThread
      const newPlanByThread = { ...state.planByThread };
      if (newPlanByThread[oldThreadId] !== undefined) {
        newPlanByThread[newThreadId] =
          newPlanByThread[newThreadId] ?? newPlanByThread[oldThreadId];
        delete newPlanByThread[oldThreadId];
      }

      // Update lastAgentMessageByThread
      const newLastAgentMessageByThread = { ...state.lastAgentMessageByThread };
      if (newLastAgentMessageByThread[oldThreadId]) {
        const oldMessage = newLastAgentMessageByThread[oldThreadId];
        const existingMessage = newLastAgentMessageByThread[newThreadId];
        newLastAgentMessageByThread[newThreadId] =
          existingMessage && existingMessage.timestamp > oldMessage.timestamp
            ? existingMessage
            : oldMessage;
        delete newLastAgentMessageByThread[oldThreadId];
      }

      // Update agentSegmentByThread
      const newAgentSegmentByThread = { ...state.agentSegmentByThread };
      if (newAgentSegmentByThread[oldThreadId] !== undefined) {
        newAgentSegmentByThread[newThreadId] = Math.max(
          newAgentSegmentByThread[oldThreadId] ?? 0,
          newAgentSegmentByThread[newThreadId] ?? 0,
        );
        delete newAgentSegmentByThread[oldThreadId];
      }

      // Update threadParentById
      const newThreadParentById = { ...state.threadParentById };
      if (newThreadParentById[oldThreadId]) {
        newThreadParentById[newThreadId] = newThreadParentById[oldThreadId];
        delete newThreadParentById[oldThreadId];
      }
      // Also update any threads that have oldThreadId as parent
      for (const [threadId, parentId] of Object.entries(newThreadParentById)) {
        if (parentId === oldThreadId) {
          newThreadParentById[threadId] = newThreadId;
        }
      }

      // Update hiddenThreadIdsByWorkspace
      const newHiddenThreadIdsByWorkspace = { ...state.hiddenThreadIdsByWorkspace };
      const workspaceHidden = newHiddenThreadIdsByWorkspace[workspaceId];
      if (workspaceHidden?.[oldThreadId]) {
        newHiddenThreadIdsByWorkspace[workspaceId] = {
          ...workspaceHidden,
          [newThreadId]: true,
        };
        delete newHiddenThreadIdsByWorkspace[workspaceId][oldThreadId];
      }
      const newUserInputRequests = state.userInputRequests.map((request) => {
        if (
          request.workspace_id !== workspaceId ||
          request.params.thread_id !== oldThreadId
        ) {
          return request;
        }
        return {
          ...request,
          params: {
            ...request.params,
            thread_id: newThreadId,
          },
        };
      });

      return {
        ...state,
        activeThreadIdByWorkspace: newActiveThreadIdByWorkspace,
        itemsByThread: newItemsByThread,
        threadsByWorkspace: newThreadsByWorkspace,
        threadStatusById: newThreadStatusById,
        activeTurnIdByThread: newActiveTurnIdByThread,
        tokenUsageByThread: newTokenUsageByThread,
        planByThread: newPlanByThread,
        lastAgentMessageByThread: newLastAgentMessageByThread,
        agentSegmentByThread: newAgentSegmentByThread,
        threadParentById: newThreadParentById,
        hiddenThreadIdsByWorkspace: newHiddenThreadIdsByWorkspace,
        userInputRequests: newUserInputRequests,
      };
    }
    case "appendReasoningSummary": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = mergeReasoningTextForThread(
        action.threadId,
        "summary" in base ? base.summary : "",
        action.delta,
      );
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "summary" in base &&
        nextSummary === base.summary
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextSummary = addSummaryBoundary("summary" in base ? base.summary : "");
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "summary" in base &&
        nextSummary === base.summary
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        summary: nextSummary,
      } as ConversationItem;
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendContextCompacted": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const id = `context-compacted-${action.turnId}`;
      if (list.some((entry) => entry.id === id)) {
        return state;
      }
      const compactedMessage: ConversationItem = {
        id,
        kind: "message",
        role: "assistant",
        text: "Context compacted.",
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, compactedMessage]),
        },
      };
    }
    case "appendReasoningContent": {
      if (!shouldAcceptReasoningDelta(state, action.threadId)) {
        return state;
      }
      const shouldInsertBeforeAssistant =
        isGeminiReasoningThread(action.threadId) &&
        !state.threadStatusById[action.threadId]?.isProcessing &&
        (state.activeTurnIdByThread[action.threadId] ?? null) === null;
      const segmentedReasoningId = resolveLiveReasoningItemId(
        state,
        action.threadId,
        action.itemId,
      );
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = findReasoningIndexById(list, segmentedReasoningId);
      const base =
        index >= 0
          ? (list[index] as ConversationItem)
          : {
              id: segmentedReasoningId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const nextContent = mergeReasoningTextForThread(
        action.threadId,
        "content" in base ? base.content : "",
        action.delta,
      );
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        index >= 0 &&
        "content" in base &&
        nextContent === base.content
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...base,
        content: nextContent,
      } as ConversationItem;
      const next = insertLiveReasoningItem(
        list,
        index,
        updated,
        shouldInsertBeforeAssistant,
      );
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "dropReasoningItems": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const filtered = list.filter((item) => item.kind !== "reasoning");
      if (filtered.length === list.length) {
        return state;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(filtered),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0) {
        const placeholder: ConversationItem = {
          id: action.itemId,
          kind: "tool",
          toolType: "commandExecution",
          title: "Command",
          detail: "",
          status: "running",
          output: action.delta,
        };
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: prepareThreadItems([...list, placeholder]),
          },
        };
      }
      const existing = list[index];
      if (!isToolConversationItem(existing)) {
        return state;
      }
      const nextOutput = mergeStreamingText(existing.output ?? "", action.delta);
      if (
        INCREMENTAL_DERIVATION_ENABLED &&
        nextOutput === (existing.output ?? "")
      ) {
        return state;
      }
      const updated: ConversationItem = {
        ...existing,
        output: nextOutput,
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "addApproval": {
      const exists = state.approvals.some(
        (item) =>
          item.request_id === action.approval.request_id &&
          item.workspace_id === action.approval.workspace_id,
      );
      if (exists) {
        return state;
      }
      return { ...state, approvals: [...state.approvals, action.approval] };
    }
    case "removeApproval":
      return {
        ...state,
        approvals: state.approvals.filter(
          (item) =>
            item.request_id !== action.requestId ||
            item.workspace_id !== action.workspaceId,
        ),
      };
    case "addUserInputRequest": {
      const exists = state.userInputRequests.some(
        (item) =>
          item.request_id === action.request.request_id &&
          item.workspace_id === action.request.workspace_id,
      );
      if (exists) {
        return state;
      }
      return {
        ...state,
        userInputRequests: [...state.userInputRequests, action.request],
      };
    }
    case "removeUserInputRequest":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.request_id !== action.requestId ||
            item.workspace_id !== action.workspaceId,
        ),
      };
    case "clearUserInputRequestsForThread":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) =>
            item.workspace_id !== action.workspaceId ||
            item.params.thread_id !== action.threadId,
        ),
      };
    case "setThreads": {
      const hidden = state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      const existingThreads = state.threadsByWorkspace[action.workspaceId] ?? [];
      const now = Date.now();
      // BUG FIX: Preserve engineSource and other info from existing threads when merging
      // This prevents loss of explicitly set engine types (e.g., Claude) when refreshing thread list
      const existingThreadById = new Map(
        existingThreads.map((thread) => [thread.id, thread]),
      );
      const newThreadIds = new Set(action.threads.map((thread) => thread.id));
      const hasPendingThreadAnchor = (threadId: string) => {
        const hasActiveTurn = (state.activeTurnIdByThread[threadId] ?? null) !== null;
        if (hasActiveTurn) {
          return true;
        }
        const itemCount = state.itemsByThread[threadId]?.length ?? 0;
        const isProcessing = Boolean(state.threadStatusById[threadId]?.isProcessing);
        if (isProcessing && itemCount > 0) {
          return true;
        }
        const lastAgentMessageTimestamp =
          state.lastAgentMessageByThread[threadId]?.timestamp ?? 0;
        const hasRecentAgentMessage =
          lastAgentMessageTimestamp > 0 &&
          now - lastAgentMessageTimestamp <= PENDING_THREAD_LAST_AGENT_ANCHOR_TTL_MS;
        if (hasRecentAgentMessage) {
          return true;
        }
        return state.userInputRequests.some(
          (request) =>
            request.workspace_id === action.workspaceId
            && request.params.thread_id === threadId,
        );
      };

      // Merge incoming threads with preserved existing info
      const visibleThreads = action.threads
        .filter((thread) => !hidden[thread.id])
        .map((thread) => {
          const existing = existingThreadById.get(thread.id);
          if (existing) {
            // Preserve engineSource if new thread doesn't have one
            const engineSource = thread.engineSource || existing.engineSource;
            // Keep the better name (prefer non-auto-generated names)
            const existingIsAutoGenerated = existing.name.startsWith("Agent ") || /^[a-f0-9]{4,8}$/i.test(existing.name);
            const newIsAutoGenerated = thread.name.startsWith("Agent ") || /^[a-f0-9]{4,8}$/i.test(thread.name);
            const name = newIsAutoGenerated && !existingIsAutoGenerated ? existing.name : thread.name;
            return { ...thread, name, engineSource };
          }
          return thread;
        });

      // BUG FIX: Also preserve threads that are currently active but not in the new list
      // (e.g., newly created Claude threads that haven't been synced to the backend yet)
      const activeThreadId = state.activeThreadIdByWorkspace[action.workspaceId];
      if (activeThreadId) {
        const activeThread = existingThreadById.get(activeThreadId);
        if (activeThread && !newThreadIds.has(activeThreadId) && !hidden[activeThreadId]) {
          // Prepend the active thread to preserve it
          visibleThreads.unshift(activeThread);
        }
      }

      // Preserve non-active pending threads that are still anchored by realtime state.
      // Without this, background CLI sessions can briefly appear as pending and then
      // disappear on the next list refresh before local history indexing catches up.
      const preservedThreadIds = new Set(visibleThreads.map((thread) => thread.id));
      const pendingToPreserve = existingThreads.filter((thread) => {
        const threadId = thread.id;
        if (!threadId.includes("-pending-")) {
          return false;
        }
        if (threadId === activeThreadId) {
          return false;
        }
        if (hidden[threadId] || newThreadIds.has(threadId) || preservedThreadIds.has(threadId)) {
          return false;
        }
        return hasPendingThreadAnchor(threadId);
      });
      pendingToPreserve.forEach((thread) => preservedThreadIds.add(thread.id));
      const mergedVisibleThreads =
        pendingToPreserve.length > 0
          ? activeThreadId && visibleThreads[0]?.id === activeThreadId
            ? [visibleThreads[0], ...pendingToPreserve, ...visibleThreads.slice(1)]
            : [...pendingToPreserve, ...visibleThreads]
          : visibleThreads;

      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: mergedVisibleThreads,
        },
      };
    }
    case "setThreadListLoading":
      return {
        ...state,
        threadListLoadingByWorkspace: {
          ...state.threadListLoadingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListPaging":
      return {
        ...state,
        threadListPagingByWorkspace: {
          ...state.threadListPagingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListCursor":
      return {
        ...state,
        threadListCursorByWorkspace: {
          ...state.threadListCursorByWorkspace,
          [action.workspaceId]: action.cursor,
        },
      };
    case "setThreadTokenUsage":
      return {
        ...state,
        tokenUsageByThread: {
          ...state.tokenUsageByThread,
          [action.threadId]: action.tokenUsage,
        },
      };
    case "setRateLimits":
      return {
        ...state,
        rateLimitsByWorkspace: {
          ...state.rateLimitsByWorkspace,
          [action.workspaceId]: action.rateLimits,
        },
      };
    case "setAccountInfo":
      return {
        ...state,
        accountByWorkspace: {
          ...state.accountByWorkspace,
          [action.workspaceId]: action.account,
        },
      };
    case "setThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: action.plan,
        },
      };
    case "settleThreadPlanInProgress": {
      const current = state.planByThread[action.threadId] ?? null;
      const next = settlePlanInProgressSteps(current, action.targetStatus);
      if (next === current) {
        return state;
      }
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: next,
        },
      };
    }
    case "clearThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: null,
        },
      };
    case "incrementAgentSegment": {
      // 当 tool item 开始时调用，增加分段计数，确保后续文本创建新的 message
      const current = state.agentSegmentByThread[action.threadId] ?? 0;
      return {
        ...state,
        agentSegmentByThread: {
          ...state.agentSegmentByThread,
          [action.threadId]: current + 1,
        },
      };
    }
    case "resetAgentSegment":
      // 当 turn 完成时调用，重置分段计数
      return {
        ...state,
        agentSegmentByThread: {
          ...state.agentSegmentByThread,
          [action.threadId]: 0,
        },
      };
    default:
      return state;
  }
}
