import type {
  ClientDocumentationBoundaryGuard,
  ClientDocumentationIconKey,
  ClientDocumentationModuleMapping,
  ClientDocumentationNode,
  ClientDocumentationPlatformCheck,
} from "./clientDocumentationTypes";

export const CLIENT_DOCUMENTATION_WINDOW_LABEL = "client-documentation";
export const CLIENT_DOCUMENTATION_WINDOW_TITLE = "Client Documentation";

export const CLIENT_DOCUMENTATION_REQUIRED_MODULE_IDS = [
  "ui-toolbars-visibility",
  "workspace-home",
  "conversation-session",
  "composer-input",
  "ai-engines-models",
  "runtime-terminal",
  "files-code-reading",
  "git-version-control",
  "spec-hub-workflow",
  "project-memory-context",
  "tasks-status",
  "search-navigation",
  "settings-center",
  "extension-capabilities",
  "notifications-updates-about",
] as const;

export const CLIENT_DOCUMENTATION_REQUIRED_UI_CONTROL_IDS = [
  "topRun.start",
  "topTool.openWorkspace",
  "topTool.runtimeConsole",
  "topTool.terminal",
  "topTool.focus",
  "topTool.rightPanel",
  "topTool.clientDocumentation",
  "rightToolbar.activity",
  "rightToolbar.radar",
  "rightToolbar.git",
  "rightToolbar.files",
  "rightToolbar.search",
  "rightToolbar.notes",
  "bottomActivity.tasks",
  "bottomActivity.agents",
  "bottomActivity.checkpoint",
  "bottomActivity.latestConversation",
  "curtain.stickyUserBubble",
  "curtain.contextLedger",
  "cornerStatus.messageAnchors",
] as const;

export const CLIENT_DOCUMENTATION_BOUNDARY_GUARDS: ClientDocumentationBoundaryGuard[] = [
  {
    id: "no-remote-docs",
    description: "不新增远程文档请求、在线 iframe、第三方文档 SDK 或 webview 外链作为基础阅读路径。",
    verification: "rg -n \"iframe|http://|https://|fetch\\(|new WebviewWindow\" src/features/client-documentation src/router.tsx",
  },
  {
    id: "no-user-doc-storage",
    description: "不新增用户可编辑文档存储、settings schema、workspace schema 或数据库迁移。",
    verification: "rg -n \"writeClientStore|AppSettings|WorkspaceSettings|migration|schema\" src/features/client-documentation src/types.ts src-tauri/src",
  },
  {
    id: "no-runtime-control",
    description: "说明窗口不得启动、停止、切换或重置 AI runtime。",
    verification: "rg -n \"runtime|start|stop|reset|terminate|kill\" src/features/client-documentation",
  },
  {
    id: "no-production-dependency",
    description: "不为说明文档窗口引入新的 production dependency。",
    verification: "git diff -- package.json package-lock.json",
  },
];

export const CLIENT_DOCUMENTATION_PLATFORM_CHECKS: ClientDocumentationPlatformCheck[] = [
  {
    id: "safe-window-label",
    platform: "cross-platform",
    description: "window label、route key、document node id 使用 ASCII kebab-case。",
    verification: "Vitest: validateClientDocumentationKey fixtures",
  },
  {
    id: "tauri-open-or-focus",
    platform: "cross-platform",
    description: "窗口打开走 Tauri WebviewWindow open-or-focus，不使用 shell open/start 或外部浏览器。",
    verification: "Vitest: openOrFocusClientDocumentationWindow constructor/getByLabel assertions",
  },
  {
    id: "macos-drag-region",
    platform: "macos",
    description: "macOS 自定义 titlebar 只让 menubar 空白区域可拖拽，按钮/树/详情区域保持交互。",
    verification: "Vitest: menubar text node drag + interactive target no-drag assertions",
  },
  {
    id: "windows-no-console",
    platform: "windows",
    description: "说明文档行为不启动进程，因此不会触发可见 console window。",
    verification: "Boundary rg: src/features/client-documentation 不包含 child_process/Command/runtime 调用",
  },
  {
    id: "path-example-parity",
    platform: "cross-platform",
    description: "路径示例同时覆盖 POSIX 与 Windows，不把单一平台路径当作唯一事实。",
    verification: "Vitest: documentation data includes Windows/POSIX notes",
  },
];

export const CLIENT_DOCUMENTATION_MODULE_MAPPINGS: ClientDocumentationModuleMapping[] = [
  {
    moduleId: "ui-toolbars-visibility",
    moduleTitle: "界面工具栏与显示控制",
    entryEvidence: "顶部运行控制、顶部工具控制、右侧活动工具栏、底部活动面板、幕布状态区、Settings > Basic > UI visibility",
    sourceEvidence: [
      "src/features/app/components/MainHeader.tsx",
      "src/features/app/components/MainHeaderActions.tsx",
      "src/features/layout/components/PanelTabs.tsx",
      "src/features/client-ui-visibility/utils/clientUiVisibility.ts",
    ],
  },
  {
    moduleId: "workspace-home",
    moduleTitle: "工作区与首页",
    entryEvidence: "Sidebar / Workspace home / Add workspace",
    sourceEvidence: ["src/features/home", "src/features/workspaces", "src/features/app/components/Sidebar.tsx"],
  },
  {
    moduleId: "conversation-session",
    moduleTitle: "对话与会话",
    entryEvidence: "主聊天画布、线程列表、会话历史",
    sourceEvidence: ["src/features/threads", "src/features/messages", "src/features/shared-session"],
  },
  {
    moduleId: "composer-input",
    moduleTitle: "Composer 输入区",
    entryEvidence: "主窗体底部 Composer",
    sourceEvidence: ["src/features/composer", "src/features/dictation", "src/features/note-cards"],
  },
  {
    moduleId: "ai-engines-models",
    moduleTitle: "AI 引擎与模型",
    entryEvidence: "Composer engine/model selector 与供应商设置",
    sourceEvidence: ["src/features/engine", "src/features/models", "src/features/vendors"],
  },
  {
    moduleId: "runtime-terminal",
    moduleTitle: "Runtime 与终端",
    entryEvidence: "Topbar runtime console / terminal action",
    sourceEvidence: ["src/features/runtime-log", "src/features/terminal", "src/features/engine"],
  },
  {
    moduleId: "files-code-reading",
    moduleTitle: "文件与代码阅读",
    entryEvidence: "右侧 Files 面板 / detached file explorer",
    sourceEvidence: ["src/features/files", "src/features/code-annotations"],
  },
  {
    moduleId: "git-version-control",
    moduleTitle: "Git 与版本协作",
    entryEvidence: "右侧 Git 面板 / Git history",
    sourceEvidence: ["src/features/git", "src/features/git-history"],
  },
  {
    moduleId: "spec-hub-workflow",
    moduleTitle: "Spec Hub 与规范工作流",
    entryEvidence: "Spec Hub 按钮 / detached Spec Hub",
    sourceEvidence: ["src/features/spec", "openspec"],
  },
  {
    moduleId: "project-memory-context",
    moduleTitle: "项目记忆与上下文",
    entryEvidence: "Memory panel / Context ledger",
    sourceEvidence: ["src/features/project-memory", "src/features/context-ledger"],
  },
  {
    moduleId: "tasks-status",
    moduleTitle: "任务与状态面板",
    entryEvidence: "Tasks / Kanban / Status panel / Session activity",
    sourceEvidence: ["src/features/tasks", "src/features/kanban", "src/features/status-panel", "src/features/session-activity"],
  },
  {
    moduleId: "search-navigation",
    moduleTitle: "搜索与导航",
    entryEvidence: "Global search / file and source navigation",
    sourceEvidence: ["src/features/search", "src/features/files/utils", "src/features/context-ledger"],
  },
  {
    moduleId: "settings-center",
    moduleTitle: "设置中心",
    entryEvidence: "Settings modal",
    sourceEvidence: ["src/features/settings"],
  },
  {
    moduleId: "extension-capabilities",
    moduleTitle: "扩展能力",
    entryEvidence: "MCP / Skills / Commands / Computer Use",
    sourceEvidence: ["src/features/skills", "src/features/commands", "src/features/computer-use", "src/features/collaboration"],
  },
  {
    moduleId: "notifications-updates-about",
    moduleTitle: "通知、更新与关于",
    entryEvidence: "Toasts / update check / about window",
    sourceEvidence: ["src/features/notifications", "src/features/update", "src/features/about"],
  },
];

const MODULE_ICONS: Record<string, ClientDocumentationIconKey> = {
  "ui-toolbars-visibility": "ui",
  "workspace-home": "workspace",
  "conversation-session": "conversation",
  "composer-input": "composer",
  "ai-engines-models": "engine",
  "runtime-terminal": "runtime",
  "files-code-reading": "files",
  "git-version-control": "git",
  "spec-hub-workflow": "spec",
  "project-memory-context": "memory",
  "tasks-status": "tasks",
  "search-navigation": "search",
  "settings-center": "settings",
  "extension-capabilities": "extensions",
  "notifications-updates-about": "notifications",
};

const MODULE_USAGE_STEPS: Record<string, string[]> = {
  "ui-toolbars-visibility": [
    "先识别当前入口属于哪个区域：标题栏左侧是顶部运行控制，标题栏右侧是顶部工具控制，右侧竖排图标是右侧活动工具栏。",
    "如果截图里的按钮不可见，进入 Settings > Basic > 界面显示，检查对应 panel 和 control 是否被隐藏。",
    "顶部运行控制用于启动或编辑 workspace launch script；它只影响脚本入口显示，不代表脚本配置被删除。",
    "顶部工具控制包含打开工作区应用、Runtime console、Terminal、Focus、右侧面板开关和客户端说明文档入口。",
    "右侧活动工具栏包含 Activity、Radar、Git、Files、Search、Notes，点击后会切换右侧 panel 的内容区域。",
    "底部活动面板包含 Tasks、Agents、Result checkpoint、Latest conversation，用于跟踪长任务状态和最近输出。",
    "幕布状态区包含用户气泡吸顶、上下文来源卡片和消息锚点，主要帮助长对话滚动时保持定位。",
    "隐藏入口只改变 UI 可见性，不清空数据、不关闭 runtime、不删除任务，也不改变 Git、Files、Search 等模块状态。",
  ],
  "workspace-home": [
    "从首页或左侧 Sidebar 进入工作区区域，先确认当前选中的 workspace 是否对应真实项目目录。",
    "如果是新项目，使用添加工作区入口选择本地目录；Windows 示例为 C:\\Repo\\client-app，macOS/POSIX 示例为 /Users/name/code/client-app。",
    "为多项目场景建立分组，把主仓库、实验 worktree、长期维护项目分别放到清晰分组中。",
    "点击工作区行切换 active workspace，等待线程列表、文件状态和 Git 状态刷新完成。",
    "需要并行处理分支时，优先创建或选择 worktree，再进入对应工作区，避免不同分支状态互相污染。",
    "如果要在外部编辑器继续处理，使用 workspace app/open entry，而不是手动复制路径。",
    "切换工作区后先确认 Composer、Git 面板和文件树都指向同一个项目，再发起 AI 任务。",
  ],
  "conversation-session": [
    "先在工作区中确认当前线程属于正确项目，避免把需求发到错误 workspace 的历史会话中。",
    "创建新线程时选择合适的引擎；继续旧线程时先浏览最近几条历史，确认上下文仍然有效。",
    "发送消息后观察 live output，长输出期间不要用刷新页面替代停止或恢复操作。",
    "如果输出失败，先读取错误提示和 runtime notice，再决定是重试、切换模型还是修复环境。",
    "需要回溯时从线程列表进入历史会话，不要复制整段 transcript 到新线程制造重复上下文。",
    "对重要结论使用任务状态、Spec 或项目记忆沉淀，避免只依赖聊天滚动记录。",
  ],
  "composer-input": [
    "在 Composer 中先写清楚目标、范围、限制和期望验证结果，减少 AI 反复追问。",
    "需要代码上下文时使用文件/路径引用，把真实文件交给模型，而不是粘贴过期片段。",
    "长任务可以拆成当前消息和 queued follow-up，保证下一步意图不会被 streaming 中断丢失。",
    "使用 note card 时先确认卡片内容仍然准确，避免把旧决策重新注入当前任务。",
    "语音输入完成后必须检查转写文本，尤其是路径、命令、模型名和大小写敏感标识。",
    "发送前检查当前 engine/model/reasoning effort，确保任务复杂度与成本匹配。",
  ],
  "ai-engines-models": [
    "从 Composer 的 engine selector 选择当前任务需要的 AI backend，例如 Claude Code、Codex、Gemini 或 OpenCode。",
    "根据任务类型选择模型：快速问答用低成本模型，复杂重构或架构判断用更强模型和更高 reasoning effort。",
    "首次使用某个供应商前进入设置检查 API key、CLI、模型映射和 doctor 结果。",
    "如果线程已经在某个引擎下运行，切换前先确认历史内容能被新引擎正确理解。",
    "遇到 control-plane、transcript 污染或历史恢复异常时，先看 runtime/loader 提示，不要直接删除会话。",
    "对比不同模型输出时保留同一输入、同一文件上下文和同一验证命令，避免比较失真。",
  ],
  "runtime-terminal": [
    "当 AI 任务无响应、启动失败或输出异常时，先打开 Runtime console 查看 runtime pool 和当前连接状态。",
    "检查 runtime notice dock 中的错误分类，区分 CLI 缺失、权限问题、模型配置问题和执行超时。",
    "需要命令行排查时打开内置 terminal，确认 shell 配置来自用户设置或平台 fallback。",
    "Windows 下关注 COMSPEC、PowerShell 和可见 console 行为；macOS/POSIX 下关注 SHELL、登录 shell 和权限提示。",
    "运行 doctor 前先确认当前 workspace 正确，避免在错误项目目录下诊断。",
    "说明窗口只负责解释入口，不启动、不停止、不 reset runtime；真实控制仍回到 Runtime/Settings。",
  ],
  "files-code-reading": [
    "打开右侧 Files 面板，先从项目根目录确认当前文件树属于 active workspace。",
    "按目录展开定位目标文件，必要时结合搜索功能快速跳转。",
    "点击文件后查看预览，代码文件优先看语法高亮和行号，Markdown/文档类文件看渲染结果。",
    "处理大文件、二进制或不支持格式时，接受降级预览，不要把空预览误判为文件不存在。",
    "需要把文件交给 AI 时，从 Composer 使用文件/路径引用，保持引用来源可追踪。",
    "需要并行阅读多个文件时打开 detached file explorer，避免主对话画布被频繁切换打断。",
  ],
  "git-version-control": [
    "进入 Git 面板前先确认 workspace 没有切错分支或 worktree。",
    "查看 status 和 diff，区分 staged、unstaged、untracked 变更，避免把无关文件混入提交。",
    "选择要提交的文件或 hunk 后再写 commit message，保证 message 描述真实变更范围。",
    "需要理解历史时打开 Git History，查看 commit、分支和 compare 结果。",
    "执行 push、reset、checkout、rebase 等高风险动作前必须看 preview 和目标分支。",
    "冲突解决时做语义融合，禁止对高风险业务文件做整文件 ours/theirs 覆盖。",
  ],
  "spec-hub-workflow": [
    "打开 Spec Hub 后先选择 active change，确认 proposal、design、specs、tasks 是否齐全。",
    "实现前阅读 proposal 和 spec delta，把需求边界、禁止项和验证门禁写清楚。",
    "进入 tasks 视图后按依赖顺序推进，完成一项就同步勾选，避免实现状态和 artifact 漂移。",
    "实现中发现需求缺口时先更新 artifact，再继续写代码，不把口头约定留在聊天里。",
    "完成后执行 validate/verify/sync；准备归档前确认主 spec 已经反映最终行为。",
    "Spec Hub 是行为规范工作台，客户端说明窗口只读展示模块说明，两者不要混用数据模型。",
  ],
  "project-memory-context": [
    "打开 Memory 或 Context ledger 前，先判断当前内容是长期规则、一次性任务信息还是临时调试线索。",
    "对长期稳定知识创建或更新 Project Memory，写清楚适用范围和触发条件。",
    "通过 Context ledger 查看当前上下文来源，确认 AI 使用的是正确文件、规则或历史结论。",
    "发现过期记忆时更新或删除，避免旧架构、旧命令、旧边界继续影响后续任务。",
    "需要追溯来源时从 ledger 跳回文件、会话或 source card，而不是凭印象复述。",
    "说明窗口不会读取用户记忆，只解释这些模块如何协作。",
  ],
  "tasks-status": [
    "长任务开始后先查看计划或 checkpoint，确认当前阶段、阻塞点和下一步动作。",
    "在 task center 或 run history 中回看历史执行，判断是继续、重试还是开新任务。",
    "使用 Kanban 或 status panel 跟踪多个并行事项，避免只靠聊天顺序判断状态。",
    "看到完成提醒后仍要检查验证命令、测试结果或业务输出，通知不等于质量门禁通过。",
    "任务失败时记录错误事实、复现条件和已尝试修复，减少下一轮重复排查。",
    "说明窗口不写入任务状态，真实状态仍由任务模块、会话和验证命令决定。",
  ],
  "search-navigation": [
    "打开全局搜索或快捷入口，先输入精确关键词，例如文件名、函数名、设置项或线程标题。",
    "根据结果类型选择跳转目标：文件进 Files，历史进会话，上下文来源进 Context ledger。",
    "搜索结果过多时缩小关键词或改用源码搜索，不要在长列表里人工滚动碰运气。",
    "跳转后检查目标 surface 是否仍在当前 workspace，避免从旧上下文跳到错误项目。",
    "如果目标不存在或已移动，使用可恢复状态返回搜索，再换关键词定位。",
    "搜索是导航工具，不是权限绕过路径；不可见或未索引内容仍需通过对应模块处理。",
  ],
  "settings-center": [
    "从 Settings modal 进入设置中心，先判断要改的是外观、快捷键、运行环境、供应商还是扩展能力。",
    "调整 UI visibility 时只隐藏入口，不假设功能本身被卸载；隐藏后需要保留回到设置的路径。",
    "修改快捷键后检查冲突提示，并在主流程中实际按一次确认生效。",
    "配置 Runtime Environment 或 provider 前先运行 doctor，确认 CLI、权限、模型映射和网络条件。",
    "保存设置后关注是否需要重启、重开窗口或下次会话生效。",
    "本说明窗口不新增 settings schema，只读取已发布的内置说明数据。",
  ],
  "extension-capabilities": [
    "进入 MCP/Skills/Commands 区域后先查看 inventory，确认哪些工具可用、禁用或需要刷新。",
    "使用 Skills 前先阅读技能描述和触发条件，避免为了用工具而用工具。",
    "执行 Commands 前确认命令作用范围、参数和可能的文件写入或外部调用。",
    "启用 Computer Use 或协作能力前检查平台权限，macOS 和 Windows 的授权边界不同。",
    "Live edit 或 collaboration mode 只在当前任务确实需要时打开，避免额外状态干扰主流程。",
    "说明窗口不读取、不执行 skill 文件，只说明这些入口如何被用户发现和理解。",
  ],
  "notifications-updates-about": [
    "观察 toast 或系统通知时先确认它来自哪个模块：runtime、任务、更新、Git 还是设置保存。",
    "任务完成提醒出现后返回对应面板查看真实结果和验证证据。",
    "触发 update check 时确认当前版本、目标版本和 release note，不要在关键任务中途盲目升级。",
    "需要排查环境时打开 About、Debug 或 diagnostics，记录版本号、平台和关键错误信息。",
    "收集诊断材料前确认不会包含 token、私密消息正文或用户不想共享的项目内容。",
    "通知是状态提示层，不能替代任务面板、runtime console 或测试命令。",
  ],
};

const getModuleIconKey = (id: string): ClientDocumentationIconKey | undefined =>
  MODULE_ICONS[id];

const getModuleUsageSteps = (id: string, workflow: string[]): string[] =>
  MODULE_USAGE_STEPS[id] ?? workflow;

const module = (
  id: string,
  title: string,
  summary: string,
  entry: string,
  purpose: string,
  features: string[],
  workflow: string[],
  notes: string[],
  relatedModules: string[],
  children: ClientDocumentationNode[],
): ClientDocumentationNode => ({
  id,
  title,
  summary,
  iconKey: getModuleIconKey(id),
  entry,
  purpose,
  features,
  workflow,
  usageSteps: getModuleUsageSteps(id, workflow),
  notes,
  relatedModules,
  children,
});

const feature = (
  id: string,
  title: string,
  summary: string,
  entry: string,
  purpose: string,
  features: string[],
  notes: string[],
  relatedModules: string[],
  workflow: string[] = [],
): ClientDocumentationNode => ({
  id,
  title,
  summary,
  entry,
  purpose,
  features,
  workflow,
  notes,
  relatedModules,
});

const uiControlFeature = (
  controlId: (typeof CLIENT_DOCUMENTATION_REQUIRED_UI_CONTROL_IDS)[number],
  title: string,
  summary: string,
  entry: string,
  purpose: string,
  features: string[],
  workflow: string[],
  notes: string[],
  relatedModules: string[],
): ClientDocumentationNode =>
  ({
    ...feature(
      controlIdToNodeId(controlId),
      title,
      summary,
      entry,
      purpose,
      features,
      notes,
      relatedModules,
      workflow,
    ),
    uiControlId: controlId,
  });

function controlIdToNodeId(controlId: string): string {
  return `ui-control-${controlId
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replaceAll(".", "-")
    .toLowerCase()}`;
}

export const CLIENT_DOCUMENTATION_TREE: ClientDocumentationNode[] = [
  module(
    "ui-toolbars-visibility",
    "界面工具栏与显示控制",
    "说明截图中的顶部按钮、右侧工具栏、底部状态区和隐藏开关。",
    "主窗体顶部标题栏、右侧活动工具栏、底部活动面板、对话幕布状态区、Settings > Basic > 界面显示。",
    "帮助用户把每个 icon 按钮和真实模块对上号，知道它在哪里、做什么、隐藏后影响什么。",
    [
      "顶部运行控制",
      "顶部工具控制",
      "右侧活动工具栏",
      "底部活动面板",
      "幕布状态区",
      "UI visibility 隐藏开关",
    ],
    [
      "先看按钮所在区域。",
      "按 tooltip 或设置项名称识别按钮。",
      "点击入口进入对应模块。",
      "需要隐藏时进入 Settings > Basic > 界面显示。",
    ],
    [
      "隐藏入口不等于禁用功能；例如隐藏 Git 入口不会改变 Git 状态。",
      "客户端说明文档入口默认隐藏，需要在顶部工具控制里手动打开。",
      "Compact/mobile 布局可能收起部分顶部按钮，桌面布局与截图最接近。",
    ],
    ["设置中心", "Runtime 与终端", "文件与代码阅读", "Git 与版本协作", "任务与状态面板"],
    [
      uiControlFeature(
        "topRun.start",
        "启动脚本按钮",
        "运行或编辑当前 workspace 的 launch script。",
        "顶部运行控制区；MainHeader 中的 LaunchScriptButton。",
        "为项目启动 dev server、test watcher、mock service 等常用脚本提供一键入口。",
        ["运行 launch script", "右键/编辑脚本", "新增多脚本入口", "保存 workspace 级脚本配置"],
        [
          "确认当前 active workspace 正确。",
          "点击播放按钮运行已有 launch script。",
          "如果未配置脚本，点击后进入设置/编辑流程。",
          "需要多个脚本时使用新增入口保存不同 label 和 icon。",
          "运行后到 terminal/runtime 相关面板观察输出。",
        ],
        ["隐藏该按钮只隐藏入口，不删除 workspace settings 中保存的脚本。"],
        ["Runtime 与终端", "设置中心"],
      ),
      uiControlFeature(
        "topTool.openWorkspace",
        "打开工作区应用",
        "在 VS Code、Finder/Explorer 或自定义应用中打开当前 workspace。",
        "顶部工具控制区；OpenAppMenu icon-only 入口。",
        "让用户快速跳到外部编辑器或系统文件管理器继续处理项目。",
        ["打开默认目标应用", "切换 open target", "记住最近选择", "支持 app/command/finder target"],
        [
          "确认标题栏显示的是目标 workspace。",
          "点击应用图标旁的下拉箭头。",
          "选择 VS Code、Finder/Explorer 或配置过的自定义目标。",
          "系统会记住本次选择作为后续默认打开目标。",
        ],
        ["Windows 和 macOS 的可用目标不同；失败时看错误 toast。"],
        ["工作区与首页", "设置中心"],
      ),
      uiControlFeature(
        "topTool.runtimeConsole",
        "Runtime console 快捷入口",
        "打开或关闭 runtime console dock。",
        "顶部工具控制区；扳手/施工图标。",
        "快速查看 runtime pool、命令预览、运行日志、错误和退出码。",
        ["runtime 状态可视化", "命令预览", "日志查看", "错误定位", "截断提示"],
        [
          "点击顶部 runtime console 图标。",
          "查看当前 runtime 是否 running/idle/error。",
          "读取 command preview 和 log，定位 CLI 或权限问题。",
          "如果输出被截断，回到 runtime/terminal 相关入口继续排查。",
        ],
        ["说明窗口不启动 runtime；该入口也不等同于 terminal shell。"],
        ["Runtime 与终端", "通知、更新与关于"],
      ),
      uiControlFeature(
        "topTool.terminal",
        "终端快捷入口",
        "打开或关闭底部 terminal panel。",
        "顶部工具控制区；TerminalSquare 图标。",
        "在当前 workspace 下使用内置终端执行命令、查看脚本输出或手动排查环境。",
        ["terminal dock", "多 terminal tab", "shell fallback", "workspace cwd", "底部高度拖拽"],
        [
          "点击顶部终端图标展开 terminal panel。",
          "确认 cwd 是当前 workspace 或仓库根目录。",
          "执行需要的命令，例如 npm test、git status 或 doctor。",
          "必要时新增 terminal tab 或关闭旧 tab。",
          "再次点击图标可收起 terminal panel。",
        ],
        ["Windows 使用 COMSPEC/custom shell，macOS/POSIX 使用 SHELL/custom shell。"],
        ["Runtime 与终端", "设置中心"],
      ),
      uiControlFeature(
        "topTool.focus",
        "聚焦模式快捷入口",
        "切换 focus/solo mode，减少侧边栏和面板干扰。",
        "顶部工具控制区；Focus 图标。",
        "让用户把屏幕空间集中到当前对话或主要工作区。",
        ["进入聚焦模式", "退出聚焦模式", "抑制右侧面板开关", "保留当前工作流状态"],
        [
          "点击 Focus 图标进入聚焦模式。",
          "阅读或编辑当前主内容区。",
          "需要查看右侧面板时先退出聚焦模式。",
          "再次点击 Focus 图标恢复常规布局。",
        ],
        ["隐藏入口不会改变当前 focus 状态；只是去掉按钮。"],
        ["对话与会话", "界面工具栏与显示控制"],
      ),
      uiControlFeature(
        "topTool.rightPanel",
        "右侧面板开关",
        "展开或收起右侧活动面板。",
        "顶部工具控制区；PanelRightOpen/PanelRightClose 或布局交换后的 PanelLeft 图标。",
        "快速释放主画布空间，或恢复 Git/Files/Search 等右侧工作区。",
        ["折叠右侧面板", "展开右侧面板", "适配 layout swapped", "不改变面板当前 tab"],
        [
          "点击 panel 图标收起右侧区域。",
          "主画布会获得更多宽度。",
          "再次点击图标恢复右侧区域。",
          "恢复后仍保留折叠前选中的 right toolbar tab。",
        ],
        ["聚焦模式下该按钮可能被隐藏，因为右侧面板不可用。"],
        ["文件与代码阅读", "Git 与版本协作", "搜索与导航"],
      ),
      uiControlFeature(
        "topTool.clientDocumentation",
        "客户端说明文档入口",
        "打开或聚焦独立 Client Guide 窗口。",
        "顶部工具控制区；BookOpen 图标，默认隐藏，可在 Settings > Basic > 界面显示中打开。",
        "在不打断主窗体工作的情况下阅读客户端每个模块的功能说明。",
        ["独立说明窗口", "open-or-focus", "左树右详情", "默认隐藏入口"],
        [
          "进入 Settings > Basic > 界面显示。",
          "打开顶部工具控制中的客户端说明文档入口。",
          "回到主窗体点击 BookOpen 图标。",
          "阅读说明窗口；再次点击会聚焦既有窗口。",
        ],
        ["关闭说明窗口不会影响主窗体会话、workspace 或 runtime。"],
        ["设置中心", "界面工具栏与显示控制"],
      ),
      uiControlFeature(
        "rightToolbar.activity",
        "活动入口",
        "切换到右侧 Activity 面板。",
        "右侧活动工具栏；Activity 图标。",
        "观察当前 workspace 的处理活动、运行状态或 live work signals。",
        ["activity live indicator", "workspace processing state", "右侧 panel 切换"],
        [
          "点击右侧 Activity 图标。",
          "查看是否有进行中的 workspace activity。",
          "根据状态决定等待、切换任务或打开更具体的任务面板。",
        ],
        ["隐藏入口不会清空已收集的 activity 数据。"],
        ["任务与状态面板", "通知、更新与关于"],
      ),
      uiControlFeature(
        "rightToolbar.radar",
        "雷达入口",
        "切换到会话雷达/运行会话面板。",
        "右侧活动工具栏；LayoutList 图标。",
        "追踪正在运行或最近完成的 session，避免长任务失联。",
        ["running sessions", "recent completed sessions", "live badge", "session tracking"],
        [
          "点击右侧 Radar 图标。",
          "查看 running session 和 recent completed session。",
          "选择目标 session 回到相关工作流。",
          "如果没有运行项，回到底部任务或会话列表确认任务状态。",
        ],
        ["隐藏入口不会停止 session tracking。"],
        ["任务与状态面板", "对话与会话"],
      ),
      uiControlFeature(
        "rightToolbar.git",
        "Git 入口",
        "切换到右侧 Git 面板。",
        "右侧活动工具栏；GitBranch 图标。",
        "查看 diff、status、commit、history 和 PR 相关状态。",
        ["Git status", "diff/commit", "history", "branch compare", "PR workflow"],
        [
          "点击右侧 Git 图标。",
          "检查当前 branch 和 git root。",
          "查看 changed files 与 diff。",
          "选择文件或 hunk 后提交，或进入 Git History 做更深分析。",
        ],
        ["隐藏入口不改变 Git 状态，也不会停止 git status refresh。"],
        ["Git 与版本协作", "文件与代码阅读"],
      ),
      uiControlFeature(
        "rightToolbar.files",
        "文件入口",
        "切换到右侧 Files 面板。",
        "右侧活动工具栏；Folder 图标。",
        "浏览 workspace 文件树、打开文件预览、插入路径引用。",
        ["文件树", "文件预览", "detached explorer", "刷新文件列表", "插入引用"],
        [
          "点击右侧 Files 图标。",
          "展开目录并选择文件。",
          "在预览区阅读内容。",
          "需要给 AI 上下文时插入文件或路径引用。",
          "文件列表异常时点击刷新或重试。",
        ],
        ["隐藏入口不会关闭已经打开的文件 tab。"],
        ["文件与代码阅读", "Composer 输入区"],
      ),
      uiControlFeature(
        "rightToolbar.search",
        "搜索入口",
        "切换到 workspace search 面板。",
        "右侧活动工具栏；Search 图标。",
        "在当前 workspace 中搜索文件、内容或来源并跳转。",
        ["workspace search", "结果跳转", "搜索状态保留", "与全局搜索互补"],
        [
          "点击右侧 Search 图标。",
          "输入关键词并运行搜索。",
          "从结果中打开文件或来源位置。",
          "结果过多时缩小关键词或切换搜索范围。",
        ],
        ["隐藏入口不改变搜索状态；全局搜索快捷键仍可独立工作。"],
        ["搜索与导航", "文件与代码阅读"],
      ),
      uiControlFeature(
        "rightToolbar.notes",
        "便签入口",
        "切换到 workspace note card 面板。",
        "右侧活动工具栏；NotebookPen 图标。",
        "查看和管理当前 workspace 的 note card、上下文片段或归档信息。",
        ["workspace notes", "note card", "归档数据", "上下文辅助"],
        [
          "点击右侧 Notes 图标。",
          "查看当前 workspace 的 note card 列表。",
          "打开需要阅读或复用的 note。",
          "必要时回到 Composer 引用相关内容。",
        ],
        ["隐藏入口不会影响 note 池或归档数据。"],
        ["Composer 输入区", "项目记忆与上下文"],
      ),
      uiControlFeature(
        "bottomActivity.tasks",
        "任务 Tab",
        "显示底部活动面板中的任务状态。",
        "底部活动面板；Tasks tab。",
        "跟踪当前任务、计划、运行历史和恢复动作。",
        ["任务状态", "run history", "retry/cancel/resume", "任务会话跳转"],
        [
          "打开底部活动面板。",
          "切换到 Tasks tab。",
          "查看任务状态、错误和可执行恢复动作。",
          "必要时打开任务会话继续处理。",
        ],
        ["隐藏 tab 不会取消任务。"],
        ["任务与状态面板", "对话与会话"],
      ),
      uiControlFeature(
        "bottomActivity.agents",
        "Agent Tab",
        "显示底部活动面板中的 Agent 状态。",
        "底部活动面板；Agents tab。",
        "观察子代理、后台代理或最近 Agent 运行状态。",
        ["agent status", "latest runs", "select subagent", "运行反馈"],
        [
          "打开底部活动面板。",
          "切换到 Agents tab。",
          "查看正在运行或最近完成的 Agent。",
          "选择目标 Agent 查看关联输出或状态。",
        ],
        ["隐藏 tab 不会停止 agent run。"],
        ["任务与状态面板", "扩展能力"],
      ),
      uiControlFeature(
        "bottomActivity.checkpoint",
        "结果 Tab",
        "显示 checkpoint、计划结果或编辑反馈。",
        "底部活动面板；Result checkpoint tab。",
        "把长任务中的阶段性结果和验证事实集中展示出来。",
        ["checkpoint facts", "plan/result", "编辑反馈", "latest verification"],
        [
          "打开底部活动面板。",
          "切换到 Result tab。",
          "查看当前阶段的输出、检查点和验证摘要。",
          "根据结果决定继续实现、补测试或回到对话。",
        ],
        ["结果展示不等于最终 CI 通过，仍需看具体验证命令。"],
        ["任务与状态面板", "Spec Hub 与规范工作流"],
      ),
      uiControlFeature(
        "bottomActivity.latestConversation",
        "最新对话 Tab",
        "显示最近对话或最新消息状态。",
        "底部活动面板；Latest conversation tab。",
        "在长任务和多面板切换时快速回看最近一次会话动向。",
        ["latest message", "conversation snapshot", "跳转回对话", "状态摘要"],
        [
          "打开底部活动面板。",
          "切换到 Latest conversation tab。",
          "查看最近用户消息或 agent 输出摘要。",
          "需要继续时跳回对应会话。",
        ],
        ["隐藏 tab 不会删除会话消息。"],
        ["对话与会话", "任务与状态面板"],
      ),
      uiControlFeature(
        "curtain.stickyUserBubble",
        "用户气泡吸顶",
        "长对话滚动时在幕布顶部保留当前用户消息提示。",
        "对话幕布区域；sticky user bubble。",
        "让用户在阅读长输出时始终知道当前回答对应哪条输入。",
        ["sticky user bubble", "长输出定位", "对话上下文提示"],
        [
          "发送消息后阅读 assistant 输出。",
          "当内容滚动较长时观察顶部吸顶用户气泡。",
          "用它确认当前输出对应的用户请求。",
        ],
        ["隐藏后只影响视觉定位，不改变消息内容。"],
        ["对话与会话", "Composer 输入区"],
      ),
      uiControlFeature(
        "curtain.contextLedger",
        "本轮上下文来源卡片",
        "展示当前回答使用过的上下文来源。",
        "对话幕布区域；context ledger/source card。",
        "帮助用户理解 AI 当前读取了哪些文件、记忆或来源。",
        ["context source", "source attribution", "ledger card", "跳回来源"],
        [
          "在对话中查看上下文来源卡片。",
          "检查本轮上下文是否包含目标文件或记忆。",
          "需要追溯时点击来源跳回对应 surface。",
        ],
        ["隐藏卡片不会删除上下文记录。"],
        ["项目记忆与上下文", "文件与代码阅读"],
      ),
      uiControlFeature(
        "cornerStatus.messageAnchors",
        "消息锚点",
        "在幕布角落展示消息跳转锚点。",
        "对话幕布角落状态区；message anchors。",
        "帮助用户在长线程中快速跳到关键消息位置。",
        ["message anchors", "快速跳转", "长线程定位"],
        [
          "在长线程中观察角落消息锚点。",
          "点击目标锚点跳到对应消息。",
          "结合 sticky user bubble 判断当前上下文位置。",
        ],
        ["隐藏锚点不会删除消息，也不会影响线程历史。"],
        ["对话与会话", "搜索与导航"],
      ),
    ],
  ),
  module(
    "workspace-home",
    "工作区与首页",
    "管理项目入口、工作区分组和最近会话。",
    "左侧 Sidebar、首页 Workspace Home、添加工作区入口。",
    "帮助用户把本地项目、worktree 与最近会话组织成可切换的工作台。",
    ["工作区列表与分组", "最近会话与项目入口", "workspace app 打开方式", "workspace 切换与基础状态"],
    ["从首页添加或选择工作区。", "在 Sidebar 中切换工作区或 worktree。", "需要外部编辑器时使用打开方式入口。"],
    ["Windows 路径示例可写作 C:\\Repo\\client-app；macOS/POSIX 路径示例可写作 /Users/name/code/client-app。", "工作区切换不会自动停止已有 runtime。"],
    ["对话与会话", "设置中心", "Runtime 与终端"],
    [
      feature("workspace-list-groups", "工作区列表与分组", "按分组管理多个项目。", "Sidebar / Workspace Home", "让多项目入口保持可发现。", ["创建分组", "移动工作区", "重命名展示别名"], ["删除或移动前确认目标分组。"], ["设置中心"]),
      feature("workspace-switch-state", "workspace 切换与基础状态", "切换当前工作区并恢复对应会话上下文。", "Sidebar workspace row", "隔离不同项目的会话、文件和 Git 状态。", ["切换 active workspace", "加载线程列表", "刷新工作区状态"], ["Windows/macOS 路径大小写和分隔符展示可能不同。"], ["对话与会话", "Git 与版本协作"]),
    ],
  ),
  module(
    "conversation-session",
    "对话与会话",
    "承载多引擎对话、历史线程和实时消息。",
    "主聊天画布、左侧线程列表、会话管理设置。",
    "让用户在 Claude Code、Codex、Gemini、OpenCode 等引擎下持续推进任务。",
    ["多引擎会话入口", "会话历史与线程列表", "实时消息流与历史加载", "会话停止、恢复与失败提示", "最新用户消息与跳转"],
    ["选择工作区和引擎。", "打开或创建线程。", "发送消息并观察实时输出。", "失败时按提示恢复或重试。"],
    ["历史加载是兜底路径，不应展示 control-plane 噪声。", "关闭说明窗口不会影响当前会话。"],
    ["Composer 输入区", "AI 引擎与模型", "Runtime 与终端"],
    [
      feature("conversation-history", "会话历史与线程列表", "浏览当前工作区已有线程。", "Sidebar thread list", "帮助用户回到历史任务。", ["线程分页", "置顶/归档", "按 workspace 隔离"], ["删除和归档是业务操作，说明窗口只描述不执行。"], ["设置中心"]),
      feature("conversation-realtime", "实时消息流与历史加载", "展示 live output 与恢复后的历史内容。", "主消息画布", "保证长任务输出可见、可追踪。", ["streaming render", "history restore", "failure notices"], ["实时输出性能会受平台和模型影响。"], ["Runtime 与终端"]),
    ],
  ),
  module(
    "composer-input",
    "Composer 输入区",
    "组织文本、文件引用、note card 和语音输入。",
    "主窗体底部 Composer。",
    "把用户意图转换成可发送给当前引擎的结构化输入。",
    ["文本输入与发送快捷键", "文件/路径引用", "note card 引用", "prompt history", "queued follow-up 与输入保留", "dictation 语音输入"],
    ["输入任务描述。", "按需附加文件、路径或 note card。", "选择发送快捷键或排队 follow-up。"],
    ["IME 输入与 streaming 期间应保持可响应。", "语音输入能力可能受平台权限影响。"],
    ["对话与会话", "文件与代码阅读", "项目记忆与上下文"],
    [
      feature("composer-file-reference", "文件/路径引用", "把项目文件作为上下文引用。", "Composer attach/reference controls", "减少手动复制路径和代码片段。", ["文件引用", "路径引用", "拖拽引用"], ["路径展示需兼容 Windows 与 POSIX。"], ["文件与代码阅读"]),
      feature("composer-dictation", "dictation 语音输入", "把语音转成输入草稿。", "Composer dictation control", "降低长文本输入成本。", ["语音录入", "模型状态", "错误提示"], ["macOS 权限和 Windows 支持状态可能不同。"], ["设置中心"]),
    ],
  ),
  module("ai-engines-models", "AI 引擎与模型", "管理引擎、模型和运行模式。", "Composer engine/model selector、供应商设置。", "让用户为不同任务选择合适的 AI backend。", ["Claude Code", "Codex", "Gemini / vendor 配置", "OpenCode", "模型选择与 reasoning effort", "engine control plane 与 runtime 隔离"], ["选择引擎。", "选择模型和 reasoning effort。", "必要时打开供应商设置或 CLI doctor。"], ["不同引擎能力和权限不同。", "control plane 数据不得污染 transcript。"], ["Runtime 与终端", "设置中心"], [
    feature("engine-selection", "模型选择与 reasoning effort", "控制当前线程使用的模型和推理强度。", "Composer selectors", "匹配任务成本和质量。", ["模型选择", "reasoning effort", "per-thread selection"], ["不可用模型需要先检查供应商配置。"], ["设置中心"]),
    feature("engine-isolation", "engine control plane 与 runtime 隔离", "隔离不同引擎的运行时和控制消息。", "Runtime backend", "避免跨引擎 transcript 污染。", ["runtime routing", "control-plane filtering", "session attribution"], ["说明窗口只描述，不参与 runtime 控制。"], ["对话与会话"]),
  ]),
  module("runtime-terminal", "Runtime 与终端", "观察 runtime、终端和环境校验状态。", "Topbar runtime console / terminal 按钮、设置中的 Runtime Environment。", "帮助定位 CLI、runtime pool 和终端 shell 问题。", ["Runtime pool", "Runtime console", "terminal shell 配置", "runtime log viewer", "runtime notice dock", "CLI doctor / 环境校验"], ["打开 runtime console。", "查看 runtime notice。", "必要时运行 CLI doctor。"], ["Windows doctor 与 macOS 权限提示不同。", "说明窗口不得启动或停止 runtime。"], ["AI 引擎与模型", "设置中心"], [
    feature("runtime-console", "Runtime console", "查看运行时连接和执行状态。", "Topbar runtime button", "提供运行态可观测性。", ["runtime visibility", "status rows", "diagnostics"], ["不要把说明窗口当成 runtime 控制台。"], ["对话与会话"]),
    feature("terminal-shell", "terminal shell 配置", "配置内置终端 shell。", "Terminal panel / Settings", "让终端使用用户期望的 shell。", ["Windows COMSPEC fallback", "macOS/Linux SHELL fallback", "custom shell path"], ["路径示例必须同时覆盖 Windows 与 POSIX。"], ["设置中心"]),
  ]),
  module("files-code-reading", "文件与代码阅读", "浏览文件树、预览文档和打开独立文件窗口。", "右侧 Files 面板、detached file explorer。", "让用户在对话旁查看项目文件与代码。", ["文件树", "detached file explorer", "文件预览与代码查看", "Markdown / 文档预览", "文件打开方式", "code annotation / line reference"], ["打开 Files 面板。", "选择文件预览。", "需要并行查看时打开 detached explorer。"], ["大文件和二进制文件可能使用降级预览。"], ["Composer 输入区", "Git 与版本协作"], [
    feature("file-tree", "文件树", "展示 workspace 文件结构。", "Right panel Files", "快速定位项目文件。", ["目录展开", "gitignored 标记", "文件选择"], ["Windows 分隔符显示要归一化。"], ["搜索与导航"]),
    feature("file-preview", "文件预览与代码查看", "展示代码、Markdown、PDF、表格等内容。", "File view panel", "在客户端内完成轻量阅读。", ["CodeMirror", "Markdown preview", "document preview"], ["不是所有格式都支持完整编辑。"], ["Composer 输入区"]),
  ]),
  module("git-version-control", "Git 与版本协作", "查看 diff、提交、历史和分支。", "右侧 Git 面板、Git History。", "支持从客户端完成常见版本控制操作。", ["Git status / diff", "commit 选择与提交", "Git history", "branch 管理与 compare", "PR workflow", "push preview / reset 相关安全提示"], ["查看变更。", "选择文件提交。", "需要时查看 history 或 PR workflow。"], ["高风险 reset/push 操作必须看 preview。"], ["文件与代码阅读", "任务与状态面板"], [
    feature("git-diff-commit", "Git status / diff / commit", "查看变更并选择性提交。", "Right panel Git", "把代码变更转为可审阅提交。", ["diff preload", "selective commit", "commit message"], ["提交前确认 staged/unstaged 范围。"], ["文件与代码阅读"]),
    feature("git-history-branch", "Git history 与 branch compare", "查看提交历史和分支差异。", "Git History view", "支持回溯、比较和 PR 准备。", ["commit history", "branch compare", "PR workflow"], ["冲突解决禁止整文件覆盖高风险文件。"], ["Spec Hub 与规范工作流"]),
  ]),
  module("spec-hub-workflow", "Spec Hub 与规范工作流", "浏览 OpenSpec change、artifact 和主 specs。", "Spec Hub 按钮、detached Spec Hub window。", "让需求、设计、任务与实现保持可追踪。", ["Spec Hub workbench", "OpenSpec change 浏览", "artifact 阅读与验证", "detached Spec Hub window", "spec root / external spec location", "verify / sync / archive 基础流程"], ["打开 Spec Hub。", "选择 change 和 artifact。", "执行 validate/verify/sync/archive。"], ["客户端说明窗口不复用 Spec Hub artifact 模型。"], ["任务与状态面板", "设置中心"], [
    feature("openspec-change-artifacts", "OpenSpec change artifact", "查看 proposal/design/specs/tasks。", "Spec Hub workbench", "支撑行为变更生命周期。", ["proposal", "design", "spec delta", "tasks"], ["实现前必须先有清晰 artifact。"], ["Git 与版本协作"]),
    feature("detached-spec-hub", "detached Spec Hub window", "独立窗口阅读规范。", "Spec Hub Open in window", "让规范阅读与主窗体并行。", ["window reuse", "reader layout", "context restore"], ["说明文档窗口与它是两个独立 surface。"], ["文件与代码阅读"]),
  ]),
  module("project-memory-context", "项目记忆与上下文", "维护项目记忆、上下文来源和引用。", "Memory panel、Context ledger。", "让长期项目知识可被捕获、查看和消费。", ["Project Memory CRUD", "自动捕获与消费", "context ledger", "source navigation", "conversation context reference"], ["打开 Memory。", "查看或编辑记忆。", "从 context ledger 跳转来源。"], ["记忆内容可能影响后续 AI 上下文。"], ["Composer 输入区", "搜索与导航"], [
    feature("project-memory-crud", "Project Memory CRUD", "管理项目记忆条目。", "Memory panel", "沉淀稳定项目知识。", ["create", "update", "delete", "consume"], ["删除前确认作用范围。"], ["设置中心"]),
    feature("context-ledger", "context ledger", "追踪上下文来源和引用。", "Context ledger surface", "解释当前上下文来自哪里。", ["source attribution", "navigation", "transition diff"], ["说明窗口只描述上下文机制，不读取用户记忆。"], ["搜索与导航"]),
  ]),
  module("tasks-status", "任务与状态面板", "管理任务、计划、checkpoint 和状态反馈。", "Tasks、Kanban、Status panel、Session activity。", "让长任务执行过程可观察、可恢复。", ["task center / task run history", "Kanban", "plan / checkpoint", "status panel", "session activity", "operation facts"], ["创建或查看任务。", "跟踪 run history。", "通过 status panel 观察 checkpoint。"], ["任务状态来自业务模块，说明窗口不写入状态。"], ["对话与会话", "Spec Hub 与规范工作流"], [
    feature("task-run-history", "task center / task run history", "查看任务运行记录。", "Task center", "帮助复盘和恢复任务。", ["run lifecycle", "history", "retry/cancel"], ["不要把说明窗口作为任务执行入口。"], ["Runtime 与终端"]),
    feature("status-panel-checkpoint", "plan / checkpoint / status panel", "展示计划、结果和检查点。", "Status panel", "减少长任务黑箱感。", ["plan view", "checkpoint facts", "latest user message"], ["状态展示不等于自动验证通过。"], ["对话与会话"]),
  ]),
  module("search-navigation", "搜索与导航", "跨文件、会话和上下文进行搜索跳转。", "Global search、文件/来源跳转入口。", "让用户快速回到目标内容。", ["全局搜索入口", "搜索 provider / ranking", "文件、会话、上下文跳转", "快捷键导航"], ["打开全局搜索。", "输入关键词。", "选择结果跳转到目标 surface。"], ["搜索结果受 provider 索引范围影响。"], ["文件与代码阅读", "项目记忆与上下文"], [
    feature("global-search", "全局搜索入口", "聚合多类搜索结果。", "Search shortcut / palette", "统一查找文件、会话、命令等内容。", ["providers", "ranking", "jump"], ["搜索不是权限绕过路径。"], ["设置中心"]),
    feature("source-navigation", "文件、会话、上下文跳转", "从结果跳回来源。", "Search result / context source", "保持阅读和操作连贯。", ["file jump", "message jump", "source cards"], ["目标不存在时应展示可恢复状态。"], ["对话与会话"]),
  ]),
  module("settings-center", "设置中心", "配置外观、快捷键、运行环境和供应商。", "Settings modal。", "集中管理用户偏好和运行前置条件。", ["基础设置", "外观与 UI visibility", "快捷键", "打开方式", "Web 服务", "邮件发送", "项目管理", "Runtime Environment", "MCP / Skills", "供应商与模型配置"], ["打开设置。", "选择左侧父入口和页内 tab。", "保存后按提示重启或下次生效。"], ["说明文档本期不新增 settings 字段。"], ["AI 引擎与模型", "Runtime 与终端"], [
    feature("appearance-shortcuts", "外观、UI visibility 与快捷键", "控制界面显示和快捷键。", "Settings > Basic", "按个人习惯调整客户端。", ["theme", "UI visibility", "shortcuts"], ["最大隐藏模式仍需保留设置恢复路径。"], ["搜索与导航"]),
    feature("runtime-provider-settings", "Runtime Environment 与供应商配置", "配置 CLI、模型和 runtime 校验。", "Settings > Runtime / Providers", "保证引擎可启动、可诊断。", ["doctor", "vendor models", "runtime pool"], ["Windows doctor 与 macOS 权限提示不同。"], ["AI 引擎与模型"]),
  ]),
  module("extension-capabilities", "扩展能力", "管理 MCP、Skills、Commands、Computer Use 和协作模式。", "Settings > MCP / Skills、Commands、Computer Use 面板。", "把外部工具能力接入客户端工作流。", ["MCP server inventory", "Skills 浏览", "Commands", "Computer Use", "Live edit preview", "Collaboration mode"], ["检查 MCP/Skills 状态。", "选择 commands 或协作模式。", "按平台能力启用 Computer Use。"], ["Computer Use 等能力有平台权限边界。"], ["设置中心", "Runtime 与终端"], [
    feature("mcp-skills", "MCP server inventory 与 Skills", "查看工具服务和技能目录。", "Settings > MCP / Skills", "理解当前 AI 可调用的工具范围。", ["server inventory", "skills browser", "refresh"], ["说明窗口不读取或执行 skill 文件。"], ["Spec Hub 与规范工作流"]),
    feature("computer-use-collaboration", "Computer Use 与 Collaboration mode", "提供屏幕/协作相关能力入口。", "Computer Use / collaboration controls", "扩展 AI 处理真实任务的能力。", ["broker status", "permissions", "mode selection"], ["macOS 权限与 Windows 支持状态必须分别说明。"], ["AI 引擎与模型"]),
  ]),
  module("notifications-updates-about", "通知、更新与关于", "展示通知、更新和版本信息。", "Toast、Update check、About window。", "让用户知道任务完成、错误、版本和诊断状态。", ["系统通知", "完成提醒", "update check", "about / version 信息", "debug / diagnostics"], ["观察 toast。", "触发更新检查。", "查看 About 或 Debug 信息。"], ["通知不等于任务成功，仍需看状态或测试结果。"], ["任务与状态面板", "设置中心"], [
    feature("notifications-completion", "系统通知与完成提醒", "提示任务完成或失败。", "Global toasts / notification plugin", "避免长任务状态丢失。", ["error toast", "completion sound", "system notification"], ["通知权限由系统控制。"], ["Runtime 与终端"]),
    feature("updates-about-debug", "update / about / diagnostics", "检查版本、关于信息和诊断证据。", "Menu / Settings / Debug", "帮助排查环境和版本问题。", ["update check", "about", "diagnostics"], ["诊断 bundle 应避免泄露 token 和消息正文。"], ["设置中心"]),
  ]),
];
