import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  buildThreeThreadReplayEventsForMinutes,
  REALTIME_REPLAY_BATCH_WINDOW_MS,
} from "../src/features/threads/contracts/realtimeReplayFixture";
import { buildRealtimePerfExtendedEvents } from "../src/features/threads/contracts/realtimePerfExtendedFixture";
import { runReplayProfile } from "../src/features/threads/contracts/realtimeReplayHarness";
import { getArgValue, isVerbose, percentile, roundMetric, writeJsonFile, type BaselineFragment } from "./perf-baseline-utils";

type DurationReport = {
  minutes: number;
  baseline: Awaited<ReturnType<typeof runReplayProfile>>;
  optimized: Awaited<ReturnType<typeof runReplayProfile>>;
  avgCpuDropPct: number;
  peakFrameDropPct: number;
  gatePass: boolean;
};

function percentDrop(fromValue: number, toValue: number) {
  if (fromValue <= 0) {
    return 0;
  }
  return ((fromValue - toValue) / fromValue) * 100;
}

function formatNumber(value: number, fractionDigits = 2) {
  return Number.isFinite(value) ? value.toFixed(fractionDigits) : "0.00";
}

function hasIntegrityFailure(result: Awaited<ReturnType<typeof runReplayProfile>>) {
  return (
    result.integrity.missingAgentMessages.length > 0
    || result.integrity.missingReasoningItems.length > 0
    || result.integrity.missingToolOutputs.length > 0
    || result.integrity.stuckProcessingThreads.length > 0
  );
}

function isQuiet() {
  return process.argv.includes("--quiet") || !isVerbose();
}

function computeExtendedMetrics(
  events: ReturnType<typeof buildRealtimePerfExtendedEvents>,
  result: Awaited<ReturnType<typeof runReplayProfile>>,
) {
  const firstAgentDelta = events.find((event) => event.kind === "agentDelta");
  const agentDeltaTimes = events
    .filter((event) => event.kind === "agentDelta")
    .map((event) => event.atMs)
    .sort((left, right) => left - right);
  const jitters = agentDeltaTimes.slice(1).map((atMs, index) => atMs - (agentDeltaTimes[index] ?? atMs));
  const deltaEvents = events.filter((event) => event.kind === "agentDelta");
  const dedupHits = deltaEvents.filter((event) => event.delta.length === 0).length;
  return [
    {
      scenario: "S-RS-FT",
      metric: "firstTokenLatency",
      value: firstAgentDelta?.atMs ?? null,
      unit: "ms",
      notes: "turn start to first assistant delta",
    },
    {
      scenario: "S-RS-FT",
      metric: "interTokenJitterP95",
      value: roundMetric(percentile(jitters, 0.95)),
      unit: "ms",
    },
    {
      scenario: "S-RS-PE",
      metric: "dedupHitRatio",
      value: deltaEvents.length === 0 ? 0 : roundMetric(dedupHits / deltaEvents.length, 4),
      unit: "ratio",
    },
    {
      scenario: "S-RS-PE",
      metric: "assemblerLatency",
      value: roundMetric(result.metrics.wallTimeMs),
      unit: "ms",
      notes: "replay reducer-path proxy latency",
    },
  ];
}

function createBaselineReportMarkdown(reports: DurationReport[], generatedAt: string) {
  const lines: string[] = [];
  lines.push("# Realtime CPU Baseline Report");
  lines.push("");
  lines.push(`Generated at: ${generatedAt}`);
  lines.push("");
  lines.push("## Scope");
  lines.push("");
  lines.push("- Input fixture: 3-thread realtime replay stream (Codex/Claude/OpenCode).");
  lines.push("- Profile: baseline (batching/no-op/incremental flags disabled).");
  lines.push("- Metrics: CPU proxy, frame proxy, event integrity.");
  lines.push("");
  lines.push("## Results");
  lines.push("");
  lines.push("| Duration | Events | Reducer Actions | CPU ms | Wall ms | P95 action ms | Max action ms | Avg actions/frame | Peak actions/frame | Integrity |");
  lines.push("|---|---:|---:|---:|---:|---:|---:|---:|---:|---|");
  for (const report of reports) {
    const integrityOk = hasIntegrityFailure(report.baseline) ? "FAIL" : "PASS";
    lines.push(
      `| ${report.minutes} min | ${report.baseline.metrics.totalEvents} | ${report.baseline.metrics.totalActions} | ${formatNumber(report.baseline.metrics.cpuTimeMs)} | ${formatNumber(report.baseline.metrics.wallTimeMs)} | ${formatNumber(report.baseline.metrics.p95ActionMs, 4)} | ${formatNumber(report.baseline.metrics.maxActionMs, 4)} | ${formatNumber(report.baseline.metrics.averageActionsPerFrame, 2)} | ${formatNumber(report.baseline.metrics.peakActionsPerFrame, 0)} | ${integrityOk} |`,
    );
  }
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("- This report is generated by deterministic replay; repeated runs produce stable semantic hashes.");
  lines.push("- CPU numbers are reducer-path proxy metrics for relative comparison, not OS task manager sampling.");
  return lines.join("\n");
}

function createAcceptanceReportMarkdown(reports: DurationReport[], generatedAt: string) {
  const lines: string[] = [];
  lines.push("# Realtime CPU Optimization Acceptance Report");
  lines.push("");
  lines.push(`Generated at: ${generatedAt}`);
  lines.push("");
  lines.push("## Acceptance Gates");
  lines.push("");
  lines.push("- 5-minute gate: average CPU drop >= 30%, peak frame load drop >= 25%.");
  lines.push("- 60-minute gate: no integrity regression and no stuck processing.");
  lines.push("");
  lines.push("## Baseline vs Optimized");
  lines.push("");
  lines.push("| Duration | Baseline CPU ms | Optimized CPU ms | Avg CPU Drop | Baseline Peak/frame | Optimized Peak/frame | Peak Drop | Semantic Hash Match | Integrity | Gate |");
  lines.push("|---|---:|---:|---:|---:|---:|---:|---|---|---|");

  for (const report of reports) {
    const semanticMatch = report.baseline.semanticsHash === report.optimized.semanticsHash;
    const integrityOk = !hasIntegrityFailure(report.baseline) && !hasIntegrityFailure(report.optimized);
    lines.push(
      `| ${report.minutes} min | ${formatNumber(report.baseline.metrics.cpuTimeMs)} | ${formatNumber(report.optimized.metrics.cpuTimeMs)} | ${formatNumber(report.avgCpuDropPct)}% | ${formatNumber(report.baseline.metrics.peakActionsPerFrame, 0)} | ${formatNumber(report.optimized.metrics.peakActionsPerFrame, 0)} | ${formatNumber(report.peakFrameDropPct)}% | ${semanticMatch ? "PASS" : "FAIL"} | ${integrityOk ? "PASS" : "FAIL"} | ${report.gatePass ? "PASS" : "FAIL"} |`,
    );
  }
  lines.push("");
  lines.push("## Per-Duration Detail");
  lines.push("");
  for (const report of reports) {
    lines.push(`### ${report.minutes}-minute replay`);
    lines.push("");
    lines.push(`- Events: ${report.baseline.metrics.totalEvents}`);
    lines.push(`- Baseline actions: ${report.baseline.metrics.totalActions}`);
    lines.push(`- Optimized actions: ${report.optimized.metrics.totalActions}`);
    lines.push(`- Action reduction: ${formatNumber(percentDrop(report.baseline.metrics.totalActions, report.optimized.metrics.totalActions))}%`);
    lines.push(`- Semantic hash: baseline \`${report.baseline.semanticsHash}\``);
    lines.push(`- Semantic hash: optimized \`${report.optimized.semanticsHash}\``);
    lines.push("");
  }

  const hasFailure = reports.some((report) => !report.gatePass);
  lines.push("## Verdict");
  lines.push("");
  lines.push(hasFailure ? "- Overall: FAIL" : "- Overall: PASS");
  return lines.join("\n");
}

async function main() {
  if (getArgValue("--profile") === "extended") {
    const events = buildRealtimePerfExtendedEvents();
    const baseline = await runReplayProfile({
      events,
      profile: "baseline",
      batchWindowMs: REALTIME_REPLAY_BATCH_WINDOW_MS,
    });
    const fragment: BaselineFragment = {
      schemaVersion: "1.0",
      generatedAt: new Date().toISOString(),
      source: "realtime-extended",
      metrics: computeExtendedMetrics(events, baseline),
      residualRisks: hasIntegrityFailure(baseline)
        ? ["Extended realtime fixture replay reported integrity failures."]
        : [],
    };
    await writeJsonFile("docs/perf/realtime-extended-baseline.json", fragment);
    if (!isQuiet()) {
      console.info("Realtime extended baseline written: docs/perf/realtime-extended-baseline.json");
    }
    return;
  }

  const durations = [5, 60];
  const reports: DurationReport[] = [];

  for (const minutes of durations) {
    const events = buildThreeThreadReplayEventsForMinutes(minutes);
    const baseline = await runReplayProfile({
      events,
      profile: "baseline",
      batchWindowMs: REALTIME_REPLAY_BATCH_WINDOW_MS,
    });
    const optimized = await runReplayProfile({
      events,
      profile: "optimized",
      batchWindowMs: REALTIME_REPLAY_BATCH_WINDOW_MS,
    });

    const avgCpuDropPct = percentDrop(
      baseline.metrics.cpuTimeMs,
      optimized.metrics.cpuTimeMs,
    );
    const peakFrameDropPct = percentDrop(
      baseline.metrics.peakActionsPerFrame,
      optimized.metrics.peakActionsPerFrame,
    );
    const semanticMatch = baseline.semanticsHash === optimized.semanticsHash;
    const integrityOk = !hasIntegrityFailure(baseline) && !hasIntegrityFailure(optimized);
    const gatePass = minutes === 5
      ? semanticMatch
        && integrityOk
        && avgCpuDropPct >= 30
        && peakFrameDropPct >= 25
      : semanticMatch
        && integrityOk
        && optimized.metrics.peakActionsPerFrame <= baseline.metrics.peakActionsPerFrame
        && optimized.metrics.totalActions <= baseline.metrics.totalActions;

    reports.push({
      minutes,
      baseline,
      optimized,
      avgCpuDropPct,
      peakFrameDropPct,
      gatePass,
    });
  }

  const generatedAt = new Date().toISOString();
  const outputDir = resolve(process.cwd(), "docs/research/realtime-cpu");
  await mkdir(outputDir, { recursive: true });

  const baselineReportPath = resolve(outputDir, "baseline-report.md");
  const acceptanceReportPath = resolve(outputDir, "acceptance-report.md");
  const rawReportPath = resolve(outputDir, "raw-report.json");

  await writeFile(
    baselineReportPath,
    createBaselineReportMarkdown(reports, generatedAt),
    "utf-8",
  );
  await writeFile(
    acceptanceReportPath,
    createAcceptanceReportMarkdown(reports, generatedAt),
    "utf-8",
  );
  const compactReports = reports.map((report) => ({
    minutes: report.minutes,
    avgCpuDropPct: report.avgCpuDropPct,
    peakFrameDropPct: report.peakFrameDropPct,
    gatePass: report.gatePass,
    baseline: {
      profile: report.baseline.profile,
      semanticsHash: report.baseline.semanticsHash,
      integrity: report.baseline.integrity,
      metrics: report.baseline.metrics,
    },
    optimized: {
      profile: report.optimized.profile,
      semanticsHash: report.optimized.semanticsHash,
      integrity: report.optimized.integrity,
      metrics: report.optimized.metrics,
    },
  }));

  await writeFile(rawReportPath, JSON.stringify({ generatedAt, reports: compactReports }, null, 2), "utf-8");

  if (!process.argv.includes("--quiet")) {
    console.info(`Realtime baseline report written: ${baselineReportPath}`);
    console.info(`Realtime acceptance report written: ${acceptanceReportPath}`);
    console.info(`Realtime raw report written: ${rawReportPath}`);
  }
}

void main();
